### ISSUE TITLE
Schema broken

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#102]
:(

I broke it. And I idiotically pushed to master instead of a new branch.

I keep getting Error #1170 on import:

```
Error
SQL query:

-- --------------------------------------------------------
--
-- Table structure for table `beers`
--
CREATE TABLE IF NOT EXISTS  `beers` (

 `id` INT( 11 ) NOT NULL AUTO_INCREMENT ,
 `name` TEXT NOT NULL ,
 `beerStyleId` INT( 11 ) NOT NULL ,
 `notes` TEXT NOT NULL ,
 `ogEst` DECIMAL( 4, 3 ) NOT NULL ,
 `fgEst` DECIMAL( 4, 3 ) NOT NULL ,
 `srmEst` DECIMAL( 3, 1 ) NOT NULL ,
 `ibuEst` INT( 4 ) NOT NULL ,
 `styleName` TINYTEXT NOT NULL ,
 `styleCatNum` TINYTEXT NOT NULL ,
 `styleCategory` TINYTEXT NOT NULL ,
 `active` TINYINT( 1 ) NOT NULL DEFAULT 1,
 `createdDate` TIMESTAMP NULL ,
 `modifiedDate` TIMESTAMP NULL ,
PRIMARY KEY (  `id` ) ,
FOREIGN KEY (  `styleName` ) REFERENCES beerStyles(  `name` ) ON DELETE CASCADE ,
FOREIGN KEY (  `styleCatNum` ) REFERENCES beerStyles(  `catNum` ) ON DELETE CASCADE ,
FOREIGN KEY (  `styleCategory` ) REFERENCES beerStyles(  `category` ) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = latin1;

MySQL said: 

#1170 - BLOB/TEXT column 'styleName' used in key specification without a key length 
```

I feel like this is _really_ obvious. But it's stumping me, and after reading 5 threads on Stack Exchange, I feel like my brain's about to explode.

Does it jump out at anybody?

**Comment by mtnbound** [comment]
Let me pull the whole new schema, but at a high level, I wouldn't join on a name. It should just join on the styleid

**Comment by thadius856** [comment]
Uh... mmkay. Lets do that then.

**Comment by mtnbound** [comment]
It's trying to join on a text column, and mySQL can't guarantee that it can join. Text fields can be very long, so you can't create foreign keys on them.

I would recommend that we should just use the col type of char with a length of 5 or so, since it's just the category which shouldn't be any longer than 3 anyway (10B)

**Comment by mtnbound** [comment]
Also, did you mean to duplicate the StyleID column? Or are you just trying not to break existing functionality?

**Comment by thadius856** [comment]
> Also, did you mean to duplicate the StyleID column? Or are you just trying not to break existing functionality?

Huh. Wow, I fucked that one up. No idea why I changed that.

**Comment by mtnbound** [comment]
This will fix it, but it's really duplicating the beerStyleId and styleId. Not sure what you were trying to do, but this keeps the current schema and adds a new one styleId. Definitely don't need both long term, but if you're trying not to break anything.

No need to have the columns style name or style category since we have a reference to the style table.

CREATE TABLE IF NOT EXISTS `beers` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`name` text NOT NULL,
`beerStyleId` int(11) NOT NULL,
`notes` text NOT NULL,
`ogEst` decimal(4,3) NOT NULL,
`fgEst` decimal(4,3) NOT NULL,
`srmEst` decimal(3,1) NOT NULL,
`ibuEst` int(4) NOT NULL,
`styleId` int NOT NULL,
`active` tinyint(1) NOT NULL DEFAULT 1,
`createdDate` TIMESTAMP NULL,
`modifiedDate` TIMESTAMP NULL,

PRIMARY KEY (`id`),
FOREIGN KEY (`StyleId`) REFERENCES beerStyles(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by thadius856** [comment]
That mostly fixed it.

The foreign key fails out because `StyleId` doesn't exist, so I had to change it to `beerStyleId`.

Also removed `styleId` because reasons you mentioned.

Prefer the name `styleId`, but don't want to break something elsewhere I don't know about.

**Comment by mtnbound** [comment]
That's what I get for writing in notepad rather than in SQL Stupid case sensitivity.

**Comment by thadius856** [comment]
Oops.
