### ISSUE TITLE
Beer Form and My Beers mismatch

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#107]
So I entered this:
![image](https://f.cloud.github.com/assets/6321429/2099887/f54e9b7e-8f41-11e3-9916-359660b6819d.png)

And got this:
![image](https://f.cloud.github.com/assets/6321429/2099924/5e636f2c-8f42-11e3-9306-4cd5ef4f76aa.png)

Thad, I know you were working on this so I wasn't sure if this was a known issue but I couldn't find it in the list.

**Comment by Skemp45** [comment]
Yeah I am pretty sure Thad hard coded that section in.

**Comment by thadius856** [comment]
Oh. Now I can see both pictures.

Yes, that's hardcoded in. Lemme see if I can get that fixed up for you.

**Comment by thadius856** [comment]
Yeahhh, can't quite figure this out. Got to the beerStyle_manager before my brain pooped out.

I'll re-attack this weekend. Hopefully I'm less confused then.

**Comment by JayUnt** [comment]
Let me know of your want me to look at it. I don't want to take away all your fun.

**Comment by thadius856** [comment]
Feel free. All of these managers and functions are killing my brain.

Format I was looking for:
"(BJCP" + `catNum` (from beerStyles table) + " - " + `category` (from beerStyles table) + ")"

**Comment by thadius856** [comment]
Tried this again, and failed again. :\

Think I got farther this time. Added a manager and a model, but it still caused the page to stop loading when I called it.

Left my commented code around line 90 in `beer_list.php`. Maybe it'll just out at somebody else.

**Comment by thadius856** [comment]
Commit: 7be65b59115c641d93850731fc4d951f358092fd

**Comment by JayUnt** [comment]
So the problem was that these fields were never added to the beer model.  You needed to add them as properties, add getters/setters and also add it to the setFromArray() function so when it comes from from the db, its set on the model.

So you know, i added catNum and category to the model, but i didn't add the other 8 min/max properties, since they are not needed yet.  They should be added, so there is no confusion later, so if you want to orient yourself with how to add them, feel free to go for it.  

You like that excuse to pass of the tedious tasks that i dont feel like doing :)

**Comment by thadius856** [comment]
I think you'll find that I have no aversion to tedium.

That said, sometimes I need a little help understanding something.

In  the case of your above post... is it in English?

Has anyone really been far even as decided to use even go want to do look more like?

**Comment by JayUnt** [comment]
Haha i can explain better.

So the manager classes we have take the the data from the database and throw them into models.  So the GetAll function gets all of the beer rows from the database.  

We then want to have an easy way to use that data.  We could just use an associative array so beer['name'] would work.  But then name is a string, which is not a good thing.  That means i could so beer['beerName'] and the code would not break, just nothing would be returned.  And we would be bashing our heads trying to figure out the problem.

So instead of using those arrays, we take each beer row from the database and put it into a specifically designed model.  So in the models folder we have a beer class.  This class has properties that line up with the table's columns.  We have getter and setters for each property, which you use to get/set the value of the beer's property.  We also have a setFromArray function which takes the array i was talking about before and sets all of that individual beer's properties.

So the problem we were having is that the model was not updated with these properties. And the setFromArray was not updated to take the values from the database row array and set the model properties with it.

Does that make more sense?

So the task is really to add the other new db fields to the model. You can pretty much take one of the other properties, and copy/rename it to the new property throughout the file.  You can look at the file difference from my commit.

**Comment by thadius856** [comment]
Ah. Ok. I'm taking notes here on how to fix this.

I tend to learn how to do these things by watching you guys do them, then I emulate it. Problem is, this is pulling from a new table, and I haven't seen how to make that happen yet.

Can you demonstrate this one for me? Specifically, `beer_list.php` line 98:

```
BJCP 1A - Light Lager</b><br><br>
```

"BJCP" - hard code
"1A" - table `beerStyles`, column `catNum`
" - " - hard code
"Light Lager" - table `beerStyles`, column `category`

The second layer of complexity is that it needs to be looked up based on the style above it. Here's how we're doing that lookup:

```
$beerStyle = $beerStyleManager->GetById($beer->get_beerStyleId());
echo $beerStyle->get_name();
```

**Comment by JayUnt** [comment]
You can take a look at the code for the style catNum and category because its committed.  Im thinking you added that last line where you are getting the $beerStyle, because i dont remember adding that.  But that is right.  We have the beerStyle's Id, so we can use the beerStyleManager to get a specific beerStyle using its id.  That returns a beerStyle model that is filled out with the data from the database, as long as there is a row with that id, and the model is setup correctly (this is the part that was/is missing).

We then use the getter function that is on the model, `$beerStyle->get_name()`, to return the value of the name property.

So after the model was updated, we now have the `$beerStyle->get_catNum()` and `$beerStyle->get_cagetory()` functions.

**Comment by thadius856** [comment]
I'm still... really... lost. :\ Not your fault.

Yes, I did try to add style. I don't think I did things right, though. Really, I should have made catNum and category, but whatever.

So, I'm staring at the model, and I'm still a little confused. Where did we tell it we wanted get_name to pull the `style` column from the table?

**Comment by JayUnt** [comment]
So the setFromArray functions in the model is the real linking.  This are the steps:
- call $beerStyleManager->GetById($beer->get_beerStyleId());

```
function GetById($id){
        $sql="SELECT * FROM beerStyles WHERE id = $id";
        $qry = mysql_query($sql);

        if( $i = mysql_fetch_array($qry) ){     
            $beerStyle = new beerStyle();
            $beerStyle->setFromArray($i);
            return $beerStyle;
        }

        return null;
    }
```

``````
- This creates a sql query to select a row from the beerStyles table based off of the id
- If there is a row, it creates an empty BeerSyle model
- It then tells to the BeerStyle object to populate itself with the array of data that was returned from the database, using the line ```beerStyle->setFromArray($i);```  $i is the returned database data in array form.
``````
- The manager then returns that fully populated object.
- So the setFromArray is the magic function that converts the database data to the object's data
- Now in the listing page, we have a fully populated BeerStyle object.  So we can use the model's function get_name() to return the name.

The code you added was exactly what was needed, we just needed to add more to it to get the rest of the info.

Any closer to getting it?

**Comment by thadius856** [comment]
Sorta. Thinking out loud here. Lets see if I get it.

So to complete what I'm doing, I know I need to query the `beerStyles` table where style = (whatever). That'll load the line and allow me to display parts of it.

I need to create a new manager in `beerStyle_manager.php`:

```
    function GetByStyle($style){
        $sql="SELECT * FROM beerStyles WHERE style = $style";
        $qry = mysql_query($sql);

        if( $i = mysql_fetch_array($qry) ){
            $beerStyle = new beerStyle();
            $beerStyle->setFromArray($i);
            return $beerStyle;
        }

        return null;
    }
}
```

Can't tell if I need to tweak the bottom half of that. Have trouble deciphering what it's doing.

Then I need to update the `beerStyle.php` model so I can pump the results to variables:

```
private $_catNum;
private $_category;

...

public function get_catNum(){ return $this->_catNum; }
public function set_catNum($_catNum){ $this->_catNum = $_catNum; }

public function get_category(){ return $this->_category; }
public function set_category($_category){ $this->_category = $_category; }

...

if( isset($postArr['catNum']) )
    $this->set_catNum($postArr['catNum']);
else
    $this->set_catNum(null);

if( isset($postArr['category']) )
    $this->set_category($postArr['category']);
else
    $this->set_category(null);

...

"catNum: " . $this->get_catNum() . ", " .
"category: " . $this->get_category() . ", " .
```

And then update `beer_list.php` to display it (here's where I start to get really fuzzy):

```
<?php 
    $beerCatNum = $beerStyleManager->GetByStyle($beer->get_beerCatNum());
    echo $beerStyle->get_catNum();
?>

<?php 
    $beerCategory = $beerStyleManager->GetByStyle($beer->get_beerCategory());
    echo $beerStyle->get_category();
?>
```

Am I overthinking this?

I still don't understand how it goes from the SQL query loading the line to pulling individual columns and saving them to variables.

**Comment by JayUnt** [comment]
You seem mostly right, except im not sure about the very first part.  Creating that new function in the manager would get beers with a specific style.  However there is no field in the beerStyles table named style so the query `SELECT * FROM beerStyles WHERE style = $style` would fail.  The getById is what we have and really all we need.  You have the beerStyleId because it was returned with the beer data previously.  The beer model has a beerStyleId property.

Once you get the beerStyle you have the catNum and the category, so you are good to output them both at that point from the $beerStyle model using $beerStyle->get_catNum() and $beerStyle->get_category().

As for the sql loading the line stuff.

Ill annotate the manager's function getById()

```
function GetById($id){
        //Build SQL query to get all beerStyles by a specific Id.  Since we know id is unique, we know this will return 1 row at most.  It might return nothing if there is no row with that id.
        $sql="SELECT * FROM beerStyles WHERE id = $id"; 

        // Execute the query against your mysql database.  The results are saved to $qry.  It might make it easier to read if $qry was named $results.  I left it at $qry because that is what it initially was from wherever it came from.
        $qry = mysql_query($sql); //

        // Use a mysql function to return the first row as an array.  If nothing was returned this will return null and the if() condition will be skipped.
        if( $i = mysql_fetch_array($qry) ){     

            // Create an empty BeerStyle object
            $beerStyle = new beerStyle();

            // Give the new BeerStyle object the array for that row to populate itself.
            $beerStyle->setFromArray($i);

            // Return the newly populated object to whoever called this function
            return $beerStyle;
        }

        // If you get this far, then no results were returned.  So we are just returning null.
        return null;
    }
```

**Comment by thadius856** [comment]
Huh.

So I just need to update the model, then slam it into `index.php`?

Seems too easy.

> ```
>         // Give the new BeerStyle object the array for that row to populate itself.
>         $beerStyle->setFromArray($i);
> ```

Witchcraft!

**Comment by JayUnt** [comment]
Haha that's the idea with managers and models. Once you get out, it should
be easy to update.

**Comment by thadius856** [comment]
Resolved. :)

Also hid all the test data behind comments.

Closing as fixed.
