### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#12]
Ok, so the next important part to this project I feel is going to be the admin/backend of the website. We need to make it EASY for our fellow non tech homebrewers to add remove and update beer. I have been a little bored at.....work ;) and put together a admin panel design, what do you guys think? I have not made any of the sub pages other than the my account page. 

http://zookeeperbrewing.com/admin
username is github
password is Pa$$w0rd

take it for a test run!
![adminp](https://f.cloud.github.com/assets/6318869/1866152/1164660c-7829-11e3-94d6-1f9aba7ce333.png)

**Comment by thadius856** [comment]
Hell. Fucking. Yes.

My only concern is this. Should you go AWOL, can you design this in a way that we (obviously not end users) can put our heads together to update when we add new features?

I'm a newb to this, so help me test my understanding here...

I'm assuming the back-end selects and updates the SQL db. Is that correct?

If so, it seems any possible configurations should be migrated away from being hardcoded in the index/css and instead moved to a separate table, perhaps 'config'. Beer should remain 'beer'. Might need a couple other tables, such as 'readings' for raw readings from sensors and 'stats' for stats.

**Comment by Skemp45** [comment]
Yes it pulls from and updated the database from the admin. I will explain more tomorrow, off to watch lost with the lady then heading bed .

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/admin/add_beer.php

OK I have the add a beer section working now!!! feel free to fill it out and submit it and then go to http://zookeeperbrewing.com to see your beer there!!!!

**Comment by Skemp45** [comment]
Changed some working around to make it an easier to understand screen

**Comment by JayUnt** [comment]
Did you use some sort of framework to build it that fast?

**Comment by Skemp45** [comment]
Yeah, 
It's a framework I bought awhile back and have updated and built the pho around it. I have rights to everything, and it's coming along nicely

**Comment by thadius856** [comment]
Right now we're licensed under Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. We inhereited this license when I grabbed the Kegerface/Kegerface source.

Eventually we'll have replaced all of his assets. I'd like to use a similar or open source license.

Is that a problem for you?

**Comment by Skemp45** [comment]
nope not at all

**Comment by thadius856** [comment]
Schweet. Good to hear.

Looked over the Admin Panel a bit. Damn man, awesome work! I know it's a work in progress at the moment, but here's a couple suggestions, purely from a (buzzed) layout/usability perspective.

Here's what I see. Probably very similar to what you see.

![untitled](https://f.cloud.github.com/assets/6320180/1874812/170a4320-78dc-11e3-953c-1ae00a720797.png)

Average Joe isn't going to know how to get the panel without being dragged there kicking and screaming. We can tell him to bookmark the URL 'til we're blue in the face, but this is an average, drunk HBTer we're talking about. Perhaps the brewery logo on index.php should link to the admin panel. And vice-versa... click the logo in the admin panel to return to the index.

The 'Add Beer' and "Edit/Remove Beer' pages could benefit from some KISS. When you land on the page, the frame should fill with the contents of the 'beers' table. Place a 'Delete' button at the far right of each row of the SQL table (hide until mouseover if you prefer), an add row below the table, a Submit button, and you're golden. TomatoUSB does this layout very well. For example:

![untitled](https://f.cloud.github.com/assets/6320180/1874856/165bb2f0-78dd-11e3-8379-aafe0fc90cd8.png)

Last thing, the Balance box (BU:GU) shouldn't be visible or fillable. Balance should be calculated automagically on the index using the following formula: BU:GU = IBU / [(1 - OG) \* 1000]

**Comment by Skemp45** [comment]
I like the idea of slamming the add edit/remove in one page KISS love it. I do like the tomato layout!!!! and YES YES YES YES I was sitting here just now thinking to myself how do we keep it simple with getting to the admin. I love the idea of reverse logos taplist logo>>goes to admin   admin logo>> goes to taplist

**Comment by Skemp45** [comment]
also, will the poured/remaining need to be there?

**Comment by thadius856** [comment]
I can't imagine Joe is going to update the Admin page after every pour, so probably not.

For those that want to update keg levels without flow meters, I guess... well... I have no idea. Suggestions welcome.

**Comment by thadius856** [comment]
On second thought, I'm not even sure why Poured and Remaining are in the beers db.

On the original CSV, there was a column 'keglvl'. You typed in a number 0-100. It would draw the picture. # poured and # remaining were both calculated on the fly assuming a 12 oz pour.

Ex: User enters 75% keg left. 5 \* .75 = 3.75 gal = 480 oz / 12 oz = 40 remaining

When we switched to SQL, $keglvl was dropped. Poured and remaining were added. Hrmmm.

**Comment by Skemp45** [comment]
ok so thinking without looking here, this might have to do with our issue with the keg images not loading properly

**Comment by thadius856** [comment]
Probably. I'll take a look and fork out anything I find. :)

**Comment by Skemp45** [comment]
feelings on the wording????? 

![adminp](https://f.cloud.github.com/assets/6318869/1875084/9caa4412-78e6-11e3-99ef-e2f41b97f85d.png)

**Comment by Skemp45** [comment]
Display will be where they can enable/disable columns, change logo, change color of certain elements such as circles around tap numbers!

**Comment by thadius856** [comment]
Hrm. 'Display' sounds weird. Visual display, like a monitor? Are we insinuating it has multiple monitor support? Is that a command? Not sure what it is.

How about 'Personalize'? Shameless stolen from Win 7.

Also, 'Gallons Per Tap', same thing. How about 'Most Popular Beers' or 'Popular Beers'.

How does Beer Rank differ?

**Comment by Skemp45** [comment]
hahah Sounds good to me

**Comment by Skemp45** [comment]
![adminp](https://f.cloud.github.com/assets/6318869/1875106/a3d0ce86-78e7-11e3-9c7c-cacb9085c5c1.png)

**Comment by thadius856** [comment]
Bravissimo!

Maybe 'Make Suggestion' -> 'Request Feature'
Maybe 'Gallond Per Tap' -> 'Popular Beers'
Maybe 'Other Help' -> 'Help'

This is your code man, I don't wanna be steppin' on toes here.

You pros have reduced me to a freakin' project manager. :P

**Comment by thadius856** [comment]
Is it possible to have the 3 main menus "Configure", "Analytics", etc. be expanded automatically on load? Does that functionality exist?

**Comment by Skemp45** [comment]
Yeah I can.......andddddddddddddddddddddddd DONE. I like that better, dont make them dig right!

**Comment by thadius856** [comment]
Damn fool. That's really freakin' fast.

Now wishing I'd done my B.S. in I.T. and could do this for a living. :\

le sigh

**Comment by Skemp45** [comment]
also all the user image redirects back to tap list,

heading to bed for the night, last night was a late one. I will check in the morning on any suggestions and hopefully wont wake up to 8 more tickets open ;)

Thanks :D haha

**Comment by JayUnt** [comment]
I was thinking that that initial keg level would be in the beer table, but there would be another table that would store each time a pour was made and the amount.  It would be a one to many relation. We would then be able to calculate the amount left using all of those numbers.  For now it is not really needed, but this would be how we store the info for the analytics of the taps.  We could eventually add who did each pour and add onto that.  Then the sensors would just throw another row into this table whenever there is a change.

As for the keg amount when you are not using flow sensors.  I think we should add another column (only if you don't have the sensors) that would have a button that the user hits when they pour a cup.  This would also add another row into that table.  It would launch a modal that has a form with just the oz amount, which would be defaulted to 12.  Or we could just assume it is 12oz each time so they don't have to type anything in, and hitting it just shows a messages that 12ozs were poured.  This is why i was thinking about using a tablet, because then the user can just tap that icon and the submit button.   

If you don't have a touch screen this wouldn't work as easily, so we might want to come up with another idea for that route.

**Comment by JayUnt** [comment]
Another suggestion I have is that adding beer to the system and assigning it to a tap are different steps.  This way if you make the same beer over and over again, you don't have to keep adding it to the system.  We would also be able to then have analytics on a specific beer over multiple kegs.  

So tap number will be removed from the the beers table, we make another table BeersTaps that has an Id, beerId, tapNum, status.  When a new beer is assigned to a tapNum that has one already, we change the pervious status to inactive and create a new row.  Then in the pour analytics table we use that beerTapId instead of beerId.  So its pointing to this specific instance, but we would be able to get analytics for anytime this beer on tap.

**Comment by Skemp45** [comment]
I was thinking that with a page that has all of your current listings on it with an open edit format and a save button, like the tomato site it would be best to be able to edit the tap id there and make which ever beers assign to what ever tap # you want. Also, we would have it broken down into 3 sections

Current Beers
(editable list of active beers)

Inactive Beers
(editable list of inactive beers)

Add  A Beer
(form to add beer)

we already have the active or inactive column in our beer table so we could use that to set a beer to inactive and have it sit off the tap list but still in the backend ready to be enabled at anytime

**Comment by JayUnt** [comment]
If we don't have this relationship table how would we keep track of this specific keg of beer's stats? Separating the active beers and inactive beers might be confusing, and what would I do if i have multiple taps of the same beer?  if they are just work off of the beer table, i could only have 1 tap per beer.  But if its a separate table, that beer can be assigned to multiple taps easily.

I'm thinking for the 3 sections it would be:
- Assign A Tap
- All Beers
- Add A Beer

In the Add A Beer section, we could have a save button and a "save and assign to tap" button, which would jump them to the Assign A Tap section. Or we could even have a tap dropdown in the form, which is just a shortcut for adding it to a tap.

**Comment by thadius856** [comment]
Jay, I like where you're going with this train of thought.

With your idea, you'd have one sheet like what we have now, but a "library" or "recipe list" or something. You enter in the beer's style, tasting notes, etc. On a separate page ("On Tap" or somesuch), you get a drop down list of all the beers in the "Library" or "Recipe List" db to select from, then assign a tap number.

The main drawback of what we have right now, Skemp, is that you have to re-type the tasting notes each time. I personally don't keep those on file, so it's be a major PITA to write it every time. UGH. In fact, it took me two hours to write the sample ones.

The only thing I might add is this. On the Recipe List or Library or whatever page, you enter Avg ABV, Avg OG, Avg IBU, etc. Because nobody hits the recipe numbers every time they brew, it could ask for Act ABV, Act OG, Act IBU, etc. on the tap selection page. If those numbers are present, it uses them. If not, it falls back to the avg ones.

Now to the kegging quantity dilemma:

I put a lot of thought into how we determine the starting quantity of beer given the equipment Joe has. What equipment does every Joe with a kegging system probably already have? A postal scale for weighing grain (not huge amounts of extract brewers that keg and would spring for flow meters) is pretty common.

My theory is that we could have a kegs table. Joe labels each of his kegs #1 thru #whatever he has with a Sharpie or something. He weighs each keg empty and enters the weight. The weights wouldn't change after each time being washed, really, so it's a one-time setup.

When Joe goes to put a new keg of beer in the keezer, he weighs it again on the scale, then enters the weight on the... _drumroll_ tap selection page, the exact same place he already would have to go to assign a tap #.

**Comment by thadius856** [comment]
Lost track of time. Dang! Gotta run!

**Comment by Skemp45** [comment]
I can see your vision now Jay and Thad,  I could get down with that idea! 

Thad-
so what is the point of the keg weight? How will this be used?

**Comment by thadius856** [comment]
Well, if you know empty keg weight and full keg weight, you can divide by
the density of water to determine exactly how much fluid is in the keg. Or
if you want to be more accurate, you can divide in the FG for super
precision. Probably exceeding the precision of the scale tho.

Some of my kegs get 4.5 gal, some get 5.2 gal. Depends on what went into
the fermenter, yanno?

**Comment by Skemp45** [comment]
ok, so they add in the weight of keg and we will take said data to calculate Total liquid amount in keg to use as our base on the keg level indicator?

**Comment by JayUnt** [comment]
Do the people who are going to be using this without a flow sensor care as much to know the exact amount they have left?  I like the idea of the weighing, but it would be easier for them to just guestimate how much they put in the keg.  Just like they are going to have to guestimate how much they are taking in each pour.  

It think they are going to be using this more as a "hey, whats on tap" and telling them very roughly when they are close to empty would be good enough.

**Comment by JayUnt** [comment]
And I like being able to add a og and abv and all of that stuff to the tap too.  Good idea

**Comment by thadius856** [comment]
Oh, no the people without flow meters won't care enough to weigh. I expect people without flow meters may just turn off the column entirely.

The weighing would be for people with flow meters. That way, you know the exact quantity you start with. If you don't know your starting quantity, the 1% accuracy of the flow meters is a moot point.

Like I said, some of my kegs get 4.5 gal, some get 5.2 gal. It's whatever comes out of the fermenter that day. And that's pretty typical from what I understand.

That's a difference of .7 gal or 14%... 85 fl oz of beer!. It would be really lame for the keg to kick the last pint (empty), with the display showing 14% left, or show empty when it had 14% left in it.

**Comment by JayUnt** [comment]
very good point.  that would suck.

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/admin/beers.php

playing around a little bit with pulling the content from the database and putting it in editable format

**Comment by thadius856** [comment]
> http://zookeeperbrewing.com/admin/beers.php
> 
> playing around a little bit with pulling the content from the database and putting it in editable format

Checked this out today. Looks different than yesterday.

Lots of info on a single page. I like it, but I think you might have an easier time if they were one per page? Whatever works for you man.

Do you plan on commiting a cursory preview of the admin page this weekend? Would love to play with it.

**Comment by JayUnt** [comment]
Yeah. I like the one beer per page idea too. Especially when we convert it to the way we were taking about of having a beer list and then an "on tap" list.

**Comment by Skemp45** [comment]
What do you mean 1 per page? I am up for what ever will look/ work the best

**Comment by Skemp45** [comment]
Hey guys I have a super cross race to attend tomorrow so I won't be able to get much work done tomorrow. But Sunday I will be able to!!!

**Comment by JayUnt** [comment]
More like what you originally had. With the add beer link that opens a form for a single beer entry.

**Comment by thadius856** [comment]
I wouldn't worry about the one page vs many on one page right now.

It'll evolve over the normal course of use anyway.

**Comment by JayUnt** [comment]
Hey guys,  i took a quick crack at the database scheme that i think will accomidate what we were talking about before.  with the taps and the beers being separate.  let me know what you think.

![raspberrypints](https://f.cloud.github.com/assets/35524/1896449/228f1f6a-7ba0-11e3-810e-ba710dc90ac1.png)

**Comment by Skemp45** [comment]
http://zookeeperbrewing.com/admin/beer_main.php
username github
password Pa$$w0rd
let me know what you think so faR?

Also, having an issue where when you click edit and change anything then submit, the og and fg get stripped to 0.000

**Comment by thadius856** [comment]
Very nice. I was doing this while laying in bed last night, in my head. Not being a pro, I didn't know there was a system/method for this. I'm re-inventing existing tools, it seems. :facepunch:

I like what ya got here. Some input, since you asked.
- We already have a `beer` table, but it's `beers`.
- In the `beers` table, can we go with `ogAvg`, `fgAvg`, `srmAvg`, `ibuAvg`?
- `tap` -> `taps` ?
- In the `taps` table: `ogAct`, `fgAct`, `srmAct`, `ibuAct`?
- I like `config`. This one will surely grow quickly.
- Can we add an `appearance` table? If we give fine-grained control later (think skinning), it would be nice to have that separate.
- For `pour` I think you mean we'd record each pour here? Perhaps `stats` would be clearer? Or `pours` or `poured`? I'm probably breaking convention here, aren't I?
- What's your vision for `user`? I can see it going about 20 different ways in my head. The RFID thing (card number 1234 belongs to abcd) is pretty obvious, but do you intent them to have login access? Maybe `drinkers` would be more descriptive? Oh, unless you want the drinkers to be able to log in and see stats. Hrmmm.

I'm probably breaking some sort of SQL naming convention throwing S's on everything, huh?

**Comment by thadius856** [comment]
Skemp, if you downloaded the latest commits I made last night, you're probably having the SQL database not line up right. I renamed/removed/added a few fields in the beers table. See the notes on #38 and #40.

**Comment by thesehands** [comment]
With the db scheme the tap list needs to yave redundancies removed. Og fg those things that exist in th beer table should not exist in the tap table. I can write a join that will give a response that would include all the info from both tables.

**Comment by thesehands** [comment]
The best part about having the beer seperate from the tap though is the abilty to have a one to many relation so one beer can be on multiple taps.

**Comment by thadius856** [comment]
There's a reason they're both there and needed. You'd add beers to the 'beer' table as would be a recipe list, so to speak. When you put something on tap, you go to a separate page and select a beer from the 'beer' table (via dropdown menu) for that tap. That way, if I like to brew, say, Haus Pale Ale a lot, I don't have to write the tasting notes every. damn. time. I put it on tap. On the 'beers' table, these would be the "average" stat... what the recipe calls for.

But when I brew it 5 times, I'll surely miss the OG/FG/SRM/IBU by a point or two either direction. So when I go to put it on the tap list, I can update a box that says what my actual OG/FG/etc was this batch and it saves to the tap table. We can have it fall back and use the "average" from the beers table if I fail to enter one using a simple if statement.

Edit: That said, they should have different names. I personally dislike the same variable name in multiple tables. That's why I suggested ogAvg for `beers` and ogAct for `taps`.

**Comment by thadius856** [comment]
Just noticed, your `pour` table doesn't have a primary key. Toss a `pourID` before `tapId`.

Can we also go from `Id` capitalization to `ID`? Is that poor form? I keep thinking it's a lowercase L.

**Comment by thadius856** [comment]
Skemp, logged in and poked around. Damn fine work, man.

![untitled](https://f.cloud.github.com/assets/6320180/1896678/8dac991c-7baf-11e3-9087-ee7a23410dfc.png)

Should these three be the same value?

![untitled](https://f.cloud.github.com/assets/6320180/1896685/e3570974-7baf-11e3-82cc-4d5d1f06c105.png)

Very nice. :)

Can we toss line breaks between these? Maybe put Tap Number, Name, Style, Notes as the first four, the rest following?

Perhaps we should add a `Back` button next to the `Submit` button for the less web-savvy users?

**Comment by thadius856** [comment]
One last, can you throw a dummy entry for `Tap List`, between `Beer List` and `Personalize`?

**Comment by Skemp45** [comment]
Added Tap List nav and re org. the update page so it shows as Tap Number, Name, Style, Notes

**Comment by thadius856** [comment]
:confused: Huh?

**Comment by Skemp45** [comment]
Can we toss line breaks between these? Maybe put Tap Number, Name, Style, Notes as the first four, the rest following?-DONE
One last, can you throw a dummy entry for Tap List, between Beer List and Personalize? -DONE

**Comment by Skemp45** [comment]
is what I ment

**Comment by thadius856** [comment]
Oh snap. You're quick!

**Comment by Skemp45** [comment]
I also fixed the issue with the og and fg stripping. It was a dumb id="" tag my bad.

**Comment by Skemp45** [comment]
and added a go back button

**Comment by Skemp45** [comment]
ok, active and inactive beers are live test it out.. http://zookeeperbrewing.com/admin/beer_main.php

**Comment by thadius856** [comment]
Just tested. Pretty schweet.

You gonna add the admin panel to the repo today?

**Comment by JayUnt** [comment]
I would suggest in the beers table, we use ogEst, fgEst, etc. (for estimate).  To me average would mean that we are going to figure out the average OG for that beer for whenever it was on a tap.

And the reason i would prefer pour or pours over stats, is because to me pours is more specific to what its holding.  Stats could really mean anything.  We are storing how much is poured at that given time.  Then to get how much is left we would take the orig amount and subtract the sum of all of the pours from that table.  That can be done easily in a query.

i haven't looked at the updated tables yet, but if you do add an id to the pour table (which is a good idea), it should
just be id and not pourId.

Ill take a look at the schema later and let you know if i have anything else.

**Comment by thadius856** [comment]
> I would suggest in the beers table, we use ogEst, fgEst, etc. (for estimate). To me average would mean that we are going to figure out the average OG for that beer for whenever it was on a tap.

Agreed.

> And the reason i would prefer pour or pours over stats, is because to me pours is more specific to what its holding. Stats could really mean anything. We are storing how much is poured at that given time. Then to get how much is left we would take the orig amount and subtract the sum of all of the pours from that table. That can be done easily in a query.

Fair enough. Can we agree on `pours` then?

> i haven't looked at the updated tables yet, but if you do add an id to the pour table (which is a good idea), it should
> just be id and not pourId.

Will do, if I get there first.

> Ill take a look at the schema later and let you know if i have anything else.

Sounds great! :D

**Comment by JayUnt** [comment]
oh yeah, and with the users, i was really thinking it was more to track what they are doing and not for them to see stats.  we dont really need it now, since we dont have that part setup, but i figured i would throw it in there.

Another way we could track ppl is how this loyality app i have does.  This company called SpotOn gave a bunch of stores in my area a tablet that they have on their counter.  When you go in to buy something, you tap the screen and it turns on the camera.  You then open the client app on your phone and it is just a qr code.  You then aim it at the tablet and it checks you in. This is another cool thing i was thinking about when i mentioned i was thinking about putting this on a tablet.   I dont expect this feature to be anywhere close to happening, but it would be cool.

Or if we have the value to turn the taps off, i was thinking we could use a qr code or even a touch pad for ppl to log into the kegerator to be able to actually pour.  Then we know who it is and we can track them then.  Would be useful for when my girl get older and want to sneak a drink.  

just thoughts that are wondering around in my head. :)

**Comment by Skemp45** [comment]
Thoughts on this back end color scheme?

![loginalt](https://f.cloud.github.com/assets/6318869/1900978/4bbc3352-7c5c-11e3-9cad-323b553bbe8e.png)

**Comment by Skemp45** [comment]
Meh IDK how I feel about it

**Comment by thadius856** [comment]
Overwhelmingly pink.

Use the raspberry color sparingly. It's very powerful.

**Comment by Boombrewer** [comment]
Agree with Thad

**Comment by Skemp45** [comment]
yeah kinda what I was feeling

**Comment by JayUnt** [comment]
Skemp, when building this admin panel, are you also building those other tables we were talking about, or do you want me to work on them.  I can work on all of them, but leave the beers table if that is the only one you are working with.  I created the config table and moved some sql files so they are in a separate folder and that the schema/production data is in one file and test data is in another.

let me know.

**Comment by Skemp45** [comment]
Jay
If you want to start on the other tables that's fine, I am using the beers and Users tables.

**Comment by JayUnt** [comment]
sound good.

**Comment by thadius856** [comment]
Skemp,

You didn't include the users table. So we can't log into our admin panels. :\

If you're having a rough time adding files, you can email them to me.

**Comment by thadius856** [comment]
Closing this issue so we can create a fresh one.
