### ISSUE TITLE
Provide Custom Colors (in lieu of SRM) for Non-Beer Items on Front Page

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#125]
Title pretty much says it all.

How can we achieve this?

Continued from #110.

**Comment by JayUnt** [comment]
Would we want any kind of drink to have a color overwritten? Or do we only want non-srm drinks top have a specified color?

**Comment by thadius856** [comment]
Well, only beer uses SRM, so... I would assume all other drinks.

"Wine SRM" (for example) doesn't seem to bring up anything useful (in Google).

**Comment by JayUnt** [comment]
The reason i ask is because if we wanted the user to be able to overwrite a beer srm too, we could just add a new field in the beer recipe form called color.  When the user updates the srm we update that field with our code, but allow them to change it if they want.  If its not a beer, they put are forced to put their color in.

The better option in my mind, comes back to having the different versions of the drink form that we discssed.  If its a beer, we keep it how it is.  If its a non-beer, we have a color dropdown, and have whatever colors we want, like red, green, etc.  or we can use a color picker plugin like this one http://bgrins.github.io/spectrum/.  We would have to add a color column to the beers/drinks table, but we could also update that with the srm color on beer save. That would then allow us to avoid having to join on the srm table when showing the tap, but that really isnt a big deal.
list.

**Comment by EmDubeu** [comment]
My vote: Non-srm drinks to have a specified color.

On Sat, Feb 8, 2014 at 6:49 PM, Jason notifications@github.com wrote:

> Would we want any kind of drink to have a color overwritten? Or do we only
> want non-srm drinks top have a specified color?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/125#issuecomment-34563816
> .

## 

Mike Wright

**Comment by thadius856** [comment]
Probably only non-beer drinks.

Seems easier to SELECT \* from <drink> (multiple tables) versus a single table mixed together, but whatever you choose, I'm sure it'll be sufficient.

**Comment by Skemp45** [comment]
Version 2?

**Comment by thadius856** [comment]
Unless you want to code it rather quickly.

**Comment by Skemp45** [comment]
;) V2 it is lol

**Comment by Skemp45** [comment]
Issue poses no consumer request and is just a stall to our current progress, this can be added as a request in a later time
