### ISSUE TITLE
Cannot select keg when adding beer to my taps

### ISSUE THREAD

**Issue by rockytoptim** [RaspberryPints/RaspberryPints#140]
Found this issue on Thadius's live site.  In the  admin screen I changed taps from 11 to something less, I think it was 6.  This change was reflected on the main taps available page.  Went back into admin screen changed taps back to 11.  Went to taps and clicked on "tap keg" button.  On the next screen I can select beer but when i get to the bottom to select keg, there is no choices available.  

I installed 0.9.0.0 pre release on my own linux and was able to replicate the issue as well.

Feel free to contact me if you need to.

![nokegtoselect](https://f.cloud.github.com/assets/6663883/2151359/11e6b460-940b-11e3-9da1-331ad86507a9.jpg)

**Comment by EmDubeu** [comment]
rockytoptim -

here's an explanation from our documenation (yet to be made available)

Putting a Beer on Tap

The "_My Taps_" section is where you place kegs on tap and remove them. The
taplist is automatically updated based on the selections you make on this
page.

In order to put a beer on tap, you must have already created a beer recipe,
have already created a keg, and have set the number of taps on your keezer.
- To update your number of taps, enter a number into the "Number of
  Taps" box and click "Update".
- To tap a keg, click the "Tap a Keg" button.
- To update a tap, click the "Update Tap Info" button.
- To replace a keg with another of the same contents, click the "New
  Keg" button.
- To indicate that a keg is empty, click the "Kick Keg" button.

Note that only kegs with certain statuses are displayed in the menu when
adding or updating a tap. We automatically hide kegs which are already in
use, need cleaning, need parts, or need repairs. If the keg you want to
choose isn't displayed in the menu, first ensure that it's not already in
use on another tap, then ensure that it does not have one of the above
statuses.

On Wed, Feb 12, 2014 at 9:31 AM, rockytoptim notifications@github.comwrote:

> Found this issue on Thadius's live site. In the admin screen I changed
> taps from 11 to something less, I think it was 6. This change was reflected
> on the main taps available page. Went back into admin screen changed taps
> back to 11. Went to taps and clicked on "tap keg" button. On the next
> screen I can select beer but when i get to the bottom to select keg, there
> is no choices available.
> 
> I installed 0.9.0.0 pre release on my own linux and was able to replicate
> the issue as well.
> 
> Feel free to contact me if you need to.
> 
> [image: nokegtoselect]https://f.cloud.github.com/assets/6663883/2151359/11e6b460-940b-11e3-9da1-331ad86507a9.jpg
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/140
> .

## 

Mike Wright

**Comment by rockytoptim** [comment]
Thanks for the feedback.  Keep up the good work.

**Comment by thadius856** [comment]
Rocky, there was also some changes to the coding of this feature last night.

My live preview may have some problems with the code right now, as I was too tired last night to completely drop/rebuilt my database.

Also, 0.9.0.0 only created to test the functionality of GitHub's Releases feature. It is most certainly not a stable or complete release. If you want to test, I suggest you download the most recent commit of the develop branch.

**Comment by JayUnt** [comment]
Seems like the kegs' statuses are not being reset after the tap is removed.
 ill look into this.

On Wed, Feb 12, 2014 at 12:31 PM, rockytoptim notifications@github.comwrote:

> Found this issue on Thadius's live site. In the admin screen I changed
> taps from 11 to something less, I think it was 6. This change was reflected
> on the main taps available page. Went back into admin screen changed taps
> back to 11. Went to taps and clicked on "tap keg" button. On the next
> screen I can select beer but when i get to the bottom to select keg, there
> is no choices available.
> 
> I installed 0.9.0.0 pre release on my own linux and was able to replicate
> the issue as well.
> 
> Feel free to contact me if you need to.
> 
> [image: nokegtoselect]https://f.cloud.github.com/assets/6663883/2151359/11e6b460-940b-11e3-9da1-331ad86507a9.jpg
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/140
> .

## 

Jason Unterman

**Comment by JayUnt** [comment]
Well i didnt get the follow up comments in my email when i read this.. WHOOPS!

But it was a bug and i fixed it on the develop branch.  The problem was that when we update the number of taps, we didnt reset the previously tapped kegs.   We are now updating those kegs to have a status of SANITIZED, so they can go right back into the keg list.  I wasnt too sure which status to use, but SANITIZED allows them to be in the tap form, so i chose that one.  If you have a better suggestion let me know.

**Comment by EmDubeu** [comment]
I agree with sanitized status.  That's how I do it in real life.
