### ISSUE TITLE
Alamode & Centipede boards

### ISSUE THREAD

**Issue by Boombrewer** [RaspberryPints/RaspberryPints#144]
First I apologize for spamming everyone with this but I didn't have a better way to do it.

For jkurl, kerber, mtnbound, skemp45, mcangeli, and thad:
Centipede boards are in but there was a shipping mix up and the alamode boards won't be in till tomorrow afternoon (after I'm out of town unfortunately).  So I will get all the boards in the mail Tuesday morning.  Sorry I couldn't get them out before the weekend.  I know all our wives would have loved it if we were all prototyping all weekend vice enjoying valentine's day.  : )

Have a good weekend.

**Comment by thadius856** [comment]
No worries, mate. We don't have code to run yet anyway. :)

Thinking of taking my wife out of town to go catch some Pliny the Younger. Of course, I'm not telling her that...

**Comment by kerber** [comment]
No worries!I've got another Arduino board and a MCP23017 that I've been developing on. Same code, different hardware.

**Comment by mtnbound** [comment]
No worries! My anniversary was today, and I would have been murdered if I had been working on this today :-)

**Comment by Skemp45** [comment]
Looks like it is no big deal man. Vday her bday and our anniversary all this week!!! Let's just say I am ok with spending some time with her.

**Comment by Boombrewer** [comment]
Haha. Glad to hear everyone is taking some time with the significant others. It's well deserved for all. Have a good weekend guys.

**Comment by kerber** [comment]
Speaking of the Arduino + MCP23017 combo... my tests are promising. I've got fully scalable Arduino code (supports 1 to 8 MCP23017) reading pulses at 1500 hz. This early test is only reading pulses from one of the MCP23017 pins. This weekend I'll set up a couple tone testers and see how it handles multiple pins pulsing simultaneously.

Don't spread the word too much, but I am extremely excited!

**Comment by thadius856** [comment]
Schweet.

These numbers are about what I expected from cursory searches before I
bought in.

**Comment by kerber** [comment]
I'm pretty confident I'd be able to get a lot higher #'s, but that's about as much as I felt like testing at 1am.

**Comment by thadius856** [comment]
If I was to run all 10 of my taps at 12 psi, I'd still be only pushing 1670
Hz. I know your pints push a lot faster, but I'm fairly confident that you
wouldn't be able to break 15 kHz on your rig.

I know there will probably be some losses polling multiple pins, but they'd
have to be massive to effect us, IMO.

**Comment by kerber** [comment]
Even if you pull from multiple taps, it would be parallel, not cumulative. The most we would ever see in practice is probably 750 Hz.

**Comment by Boombrewer** [comment]
Kerber - are you just writing the code for the arduino or both?

If we're gonna be writing in C, I need to kind those how-to's and learn to use this collaboration stuff.

**Comment by kerber** [comment]
I'm working on all the hardware integration stuff, so no worries. The Arduino is pseudo-C and the RPi side is all Python.

**Comment by kerber** [comment]
Once I get it to a more stable state, I'll be adding it to GitHub

**Comment by JayUnt** [comment]
Hey,

Not to pile all of these questions on you, but are you working on/thinking about how this data is going to get into the database?

I was thinking about having a page that your stuff would just call with certain parameters, and then the page would take care of putting it all into the database, kinda like an REST API.  I like the idea of the app putting the data in because it allows others to use different hardware if they choose and it comes into the system the same way. You would then not have to worry about inserting the created date and other extra info that is not pertinent to the flow sensors.  And if we change the database structure, all we would do is have to update the api and your code would not have to be touched.

This is something i can work on, even before your hardware stuff is functional.

Let me know

**Comment by kerber** [comment]
By all means, Jay, pile the questions on!

This would definitely be a good place to make use of an API. It will keep things so much easier to maintain if all the DB code and logic is on one place.

I'm fairly proficient in PHP and database design, so I was just going to handle it. I would definitely appreciate the collaboration, though. I need to start looking into the existing DB structure and decide where to store keg volumes, tap to MCP23017 address/pin# relations, and calibration info.

Obv we'll want some place in the admin page where we can set address, pin, and pulse/liter for each tap. Then, for each beer, we'll probably have them put in the weight of the empty keg and weight of the full keg. Using the FG and the weight diff, we can calculate initial fluid volume.

When a pour finishes, the Arduino passes on a message containing the MCP23017 address, pin #, and pulse count. Using the address and pin #, the code will map that to a tap. Then, using the calibration data, it will calculate the pour volume and store the total pulled amount. I just like the idea of keeping the original volume intact and total poured separate for the sake of metrics.

The main questions at this point are which parts will be done in python and which will be done in PHP, as well as what the DB structure will be.

**Comment by JayUnt** [comment]
That's exactly what we thought when we setup the database. We have a taps table where they put the starting volume. Then we have a pours tale that had a FK to the taps table. So for each pour, we insert a row into the pours table.  To get the current volume we just take the initial volume and minus the SUM(amount) fit the pours.

There is a db view that does this when getting the taps for index.php.

**Comment by kerber** [comment]
Great minds! I've totally ignored the web/DB side of this thus far. You guys are rocking it!

**Comment by kerber** [comment]
We'll just need to add the addr/pin# relation and calibration to the tap table.

**Comment by kerber** [comment]
It probably makes the most sense to do all the mapping and calibration info in PHP, since it has direct DB access.

The Python can just act as the layer in between the hardware and web, taking the message from the Arduino and passing the same info to the API.

**Comment by JayUnt** [comment]
So then the php would get the number of pulses and figure what that equals in ounces?

**Comment by thadius856** [comment]
> Even if you pull from multiple taps, it would be parallel, not cumulative. The most we would ever see in practice is probably 750 Hz.

I think you mean series...

I was thinking about bars, where multiple taps may be pulled in parallel.

Event booths are even worse, often with only 1 tap per person and 20 people. Obviously, they're not our target audience, but still... that's where my mind went. :)

> So then the php would get the number of pulses and figure what that equals in ounces?

_shudder_ Sounds like we're adding overhead and ugly to the frontend needlessly. Do we really want to calculate all of this every time we refresh the view or page? Seems like it would be better to convert to volume before tossing it in the db, as the calibration values may change over time (and would affect previous measurements). Besides, wouldn't we want volume recorded instead of pulses for the metrics side of the house?

**Comment by JayUnt** [comment]
Yeah, when I was first thinking about it, I was thinking the arduino would calculate the ounces poured and then send it over. I was seeing what kerber was thinking.

If we keep the calculations in the arduino side, the Api becomes more generic, which is a good thing.

**Comment by thadius856** [comment]
I don't have a preference between the Arudino vs the Pi making the pulse -> volume calculation, but I do think that it should be done before we commit data to the DB. Seems really silly to put that step off until we're trying to draw the display.

**Comment by JayUnt** [comment]
Agreed. The db should just get how many ounces was poured. We don't care
about pulses at that point.

**Comment by kerber** [comment]
> I think you mean in series

I meant cumulative... as in adding the pulses together. Series would refer to plumbing, which was out of the scope of this conversation. Either way, you understood my point.

We definitely do not want to do the calculations on the Arduino. It would be a really bad design choice to keep calibration logic down on that low level.

It makes far more sense for the calculations to be done wherever the DB layer is. Otherwise, every time a pour is received by Python, it has to call the API to find the tap address. Then, it has to call the API to get the calibration data. Then it has to call the API to store the value. Since those calculations are so dependant on dynamic data, they need to be pulled from the DB every time. 

I completely agree that the oz for the pour should be what's stored in the table, but that calculation can be done in PHP by the API on store. It doesn't need to be done on render. That same step could calculate the remaining volume and store that along with the keg info, but I do want to keep the initial volume and pours intact and separate. Talking about doing calculations in PHP does not mean we're talking about doing things on render.

Speaking of which, the plan isn't to have the page refresh to update, is it? Are we not planning on making any use of web sockets?

**Comment by thadius856** [comment]
> Talking about doing calculations in PHP does not mean we're talking about doing things on render.

This was the source of my confusion. Sry.

> Speaking of which, the plan isn't to have the page refresh to update, is it? Are we not planning on making any use of web sockets?

I see jQuery in the repo, so I was guessing jQuery and AJAX. But I don't think we ever got a firm agreement on what we wanted to do... did we?

**Comment by kerber** [comment]
We're all good :)
I've still not taken any time to get familiar with the existing code base. I'll probably get to that some time today or tomorrow. Right now, I'm still working on stress testing the hardware and Arduino code.

**Comment by Boombrewer** [comment]
Boards were mailed out today.  For those on the west coast, they should be there in a few days.  Sorry east coast guys.

**Comment by jkurl** [comment]
Awesome thanks man. Should have mine before I head back to Seattle in
Sunday. Got my flow meters as we'll. thanks again

**Comment by thadius856** [comment]
(>'-')> <('-'<) ^(' - ')^ <('-'<) (>'-')>

**Comment by Skemp45** [comment]
You rock boombrewer. I am closing this issue though to clear up the issues section to prepare for release.

**Comment by kerber** [comment]
Just got my boards in! I'm so excited to dig in! Thanks again, Boombrewer! Unfortunately, I seem to be the unfortunate recipient of a partially unpopulated board! I'm missing one of my MCP23017 chips. I've been emailing back and forth with the creator at Macetech, so I just shot him an email asking if I could swap it out. I'll let you know how the process goes, as it's something our users may potentially have to deal with.

Also note - the boards come without the headers attached. Some soldering required :)
