### ISSUE TITLE
Big Blue

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#156]
the big blue button on the front of our website should be changed from contribute on github to Download RaspberryPints. and it can just link to the zip file from github. 

thoughts? 

no reason to send them to another website to get the download. we are still letting github host the file so if we change the code its still pulling from the link.

**Comment by jkurl** [comment]
If we keep them in one area majority of the time it will help minimize
confusion plus accidentally closing the wrong browser window. If we are
going to use one particular raspbian install it might not be a bad idea to
do the same thing for the download of the pi OS. The only thing they would
have to go to another sight for at this point would be the SD card
formatting tool that we have them download. I personally don't use it since
I use macs.

**Comment by thadius856** [comment]
Agree, but we can't just link to a zip because the filenames change constantly.

The Releases page would be a good destination:

https://github.com/RaspberryPints/RaspberryPints/releases

**Comment by jkurl** [comment]
Yeah I forgot that the OS version is changed in each update.

**Comment by thadius856** [comment]
Done. Closing as completed.
