### ISSUE TITLE
Names on non-beers display with an _ in the taplist

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#179]
From: Sean Power (Arglesnaf on HBT) sean@seanjpower.com
Subject: Names on non-beers display with an _ in the taplist

Message Body:
I realize this is a compromise to get these items to show at the bottom of the dropdown.  Perhaps the displaying PHP or a stored proc / view with triggers can strip the "_Non-Beer:" before it is presented to the front end?

I also forsee a need to add other styles beyond the BJCP ones since BJCP does have catch all styles.

**Comment by thadius856** [comment]
Yeah, additional styles would be easy enough. We'd definitely want to keep the custom ones somehow separate from the ones we have now, since those need to remain what uneditable for BeerXML support down the road. Separate table? Sounds overkill. Probably an additional column on beerStyles to add "beerXML" or somesuch.

I'll look at stripping the _.

**Comment by thadius856** [comment]
Committed. Was a pretty easy fix. Just wrapped it with str_replace:

`<?php echo str_replace("_","",$string); ?>`
