### ISSUE TITLE
Move to an MVC framework?

### ISSUE THREAD

**Issue by paulcanning** [RaspberryPints/RaspberryPints#199]
A bit of a large request, but something I think you'd appreciate in the long run.

I'd like to suggest you move the code into an MVC framework, my suggestion being CodeIgniter (there are others of course, CakePHP, Laravel etc. I just like CI that's all)

It's very quick to get up and running and a project like this seriously wouldn't take too long to convert.

It would mean the project is nice and tidy, a template engine could be used as well and makes life easier for people wanting to contribute, as MVC's are typically easier to navigate through then the way the current project is set out.

It'd most probably have to be for v10 or something haha, but please, consider it?

**Comment by JayUnt** [comment]
Hey,

When i wrote the managers and models i had MVC in mind.  The reason i didn't go a full MVC framework route is that i didnt want to prevent the other code contributors from being able to contribute because they dont know what an MVC is.  

Another reason is because I've never used a php MVC.  I've used Spring MVC for Java and ASP MVC.  I've thought about the idea of at least bringing in an ORM so we wouldn't have to make all of the tedious get and set queries.  I feel like doing the ORM is simple enough for the others to pickup, but a full fledged MVC might be too much.

We could even bring in a templating engine, and just bring in the different mvc functionality piece at a time.

But then again, now is the time to convert it to MVC when there isnt as much code to convert over...

decision, decisions

**Comment by paulcanning** [comment]
Trust me when I say, if I can use CI, anyone can haha!

I have used it for various projects, and like I mentioned, you could get this project converted in a mater of days, I'm sure of it.

I'd recommend heading over to the CI website and having a look around and even try installing it and having a quick blast, you can grasp the basic in minutes (I've even crash-coursed a friend in CI before to get him to help me out with some stuff)

**Comment by JayUnt** [comment]
Ive heard of it before but never used it.  I actually wouldn't mind learning a php MVC, so im leaning towards yes. But I definitely want some of the other guy's input on this before we spend the time.  

The other thing we have to consider is that we are currently developing other features.  So we would have to coordinate with those features, since they are being coded using the current structure.  Not a big deal, just something to consider.

And like i said before, the earlier we make this change, the easier it is to do.

**Comment by paulcanning** [comment]
Understood. I hope the other folks involved are keen for this.

Combined with bootstrap, you'll end up with a very nice product in the end :)

**Comment by thadius856** [comment]
I really have no opinion either way.

If its free, doesn't conflict with our licensing, and improves our process
or product, I'm all for it.

Ill have extremely limited time the next six weeks, so be prepared to step
me thru it when I get back.

**Comment by Skemp45** [comment]
This is being discussed in #223 so this is now redundant, closing this issue
