### ISSUE TITLE
IBU hop display adjustment

### ISSUE THREAD

**Issue by shepikoff** [RaspberryPints/RaspberryPints#204]
This may be just my personal taste on beers and what an average bitterness is. Currently the scale is 0 - 100 for IBU and a 50 IBU beer would appear to be a medium hopped beer and the hop icon would be 50% full.

I doubt that many people could perceive any difference over 80 IBU and most would probably call a 50 IBU much more than average bitterness. I propose making 40-44 IBU the mid-point of the hop icon, maybe use a 1.15 or 1.20 multiplier in the IBU display calculation. This should also help any 10-20 IBU beers show up as barely bitter on the hop display. Any thoughts?

```
Line 185 of master
<div class="ibu-indicator"><div class="ibu-full" style="height:<?php echo $beer['ibu'] > 100 ? 100 : $beer['ibu'] * 1.2; ?>%"></div></div>

```

**Comment by thadius856** [comment]
Well, 100 being the full hop fill was chosen because that's about the threshold of human bitterness perception.

I like your direction of thought, and that's why I originally coded the BU:GU readout above the IBU graphics. 1 is balanced, below 1 is malty, above 1 is hoppy.

How about, instead, we were to offer an option that changes the hop icon into an illustration of the BU:GU balance of the beer? Maybe some old timey scales with hops on one side and grain on the other? Throwing ideas out here.

**Comment by Skemp45** [comment]
^ I'm picking up what you're putting down

**Comment by shepikoff** [comment]
I think the current icon and layout is great. I guess I'm considering two audiences. The quantitative values are great for the enthusiasts among us, and the icon is for the folks who have no clue what IBUs or BU:GU mean. So I was thinking that the hop should be more of a qualitative indicator using a  bezier curve scale than a linear scale. Don't know if my multiplier idea accomplishes this though.

**Comment by thadius856** [comment]
I understand what you mean. The problem I feel with either scale is that they are meaningless on their own.

A 30 IBU cream ale is a pretty bitter experience, while a 30 IBU Barleywine would be cloyingly sweet. This article does a better job of illustrating this than I can, and is the reason why BU:GU appears on the front-end to begin with: http://www.pencilandspoon.com/2012/11/forgot-ibu-think-about-bugu.html

I agree with you that the images should be for the casuals, while the numbers should be for the diehards. Taking the scales a bit farther, what if we expanded it to 5 different images. One level, two tipping slightly in either direction, two tipping heavily in either direction. Would could put accompanying text above:

Very Hoppy
Slightly Hoppy
Balanced
Slight Malty
Very Malty

**Comment by mtnbound** [comment]
I really like the thought of the BU:GU ratio for the hop graphic. Not that we need to go into details of IBU and BU:GU on the display, but BU:GU probably makes more sense based on what DigitalSteel is looking for. 

I was just looking at my display, and I have a huge RIS that has nearly the same hop graphic as my IIPA. Clearly they are different, with one being a 1.27 ratio and a .67 ratio, so if the graphic should be a representation of what a drinker will experience the ratio would be better. Even with a curve, it would probably not make sense.

Obviously as config item would make it work for everyone

**Comment by thadius856** [comment]
Looks like I said 1.0 was the point of balance. It's really closer to 0.50.

RGR is a cool system, but doesn't work very well when you get into diverse specialty categories (vegetal, spice, smoked, wood-aged, fruit, non-alcoholic, gruit, gluten free, etc etc) because 1) there's often no established averages/means and 2) even when there are, they're often paired with very large standard deviations.

**Comment by Skemp45** [comment]
closing to clean up issue board and get project back on task
