### ISSUE TITLE
shop.raspberrypints.com

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#220]
Ok, I know we have talked about this before but lets re analyze now. HomebrewTalk has been good to us for traffic but they are limiting on what we can do without buying the proper membership, word is out now and we can announce that we will be leaving HBT and if they want updates to sign up for our email list or Facebook or twitter page. But we are getting tons of traffic now and its time we revisit what this can be for all of us. I suggest a **shop.raspberrypints.com** where we can sell parts, pre configured raspberry pi's, stickers, shirts and more. Also allowing us to take donations to make this product become even more than it is now. I have spent the last week and a half focusing on trying to run RaspberryPints Facebook page and website like a business and it is looking good and I feel confident we can turn this into something good for us founding members. The good thing is we are not selling RaspberryPints code at all we are providing Raspberry pi's pre-configured with it on there this would be fine. Lets talk about this together and see what we think

**Comment by Skemp45** [comment]
Things to consider With cost--
**Running costs**\- Hosting, Email, SSL, domain
**Marketing**\- Facebook Ads, google Adwords, HBT advertising
**Product Development**-More boards, more pi's, fund the things you need to make Pints better!!!

**Comment by JayUnt** [comment]
The only piece of that I'm weary of is the "Paying out our time" part.  I think that can get hairy on how much everyone gets, and some people might think they do more and should get more than some other people, and then there is a rift and all shit hits the fan.  I would love to get paid for this, but i dont think its worth the risk for that.  I would rather put the money back into the hosting and all of that.  and if we do get enough, get a hbt vendor account.

**Comment by Skemp45** [comment]
Yeah That was more of a filler lol. Lets just remove that

**Comment by Skemp45** [comment]
but yeah just keep dumping money into this and making it as big as it should be. We are really just limiting ourselves at this point by not growing just to stay on HBT and if we leave HBT for a while we can earn the money to move back to HBT with a vendor account

**Comment by Skemp45** [comment]
Plus if we made enough we could do a Vendor giveaway, how cool would that be

**Comment by kerber** [comment]
I think this has some potential, but should probably wait until we have some more features, like V2. I do wonder about the usefulness of Facebook advertising though: http://www.youtube.com/watch?v=oVfHeWTKjag

**Comment by Skemp45** [comment]
Very good video, Facebook ads are very dangerous, it is all about targeting and knowing your users. You should not run an add that will reach millions of people, you want to focus down on multiple interests. Its all about user engagement.I will be reviewing our likes from the first add I ran and report back.

**Comment by thadius856** [comment]
> Plus if we made enough we could do a Vendor giveaway, how cool would that be

Pretty sure you need a Vendor Membership for that...

**Comment by thadius856** [comment]
Other than custom boards and pre-imaged SD cards, I can't think of anything worth selling, honestly.

**Comment by JayUnt** [comment]
I would love a shirt, sweatshirt and stickers. But even if we don't sell
then, I think we should get some for ourselves :-)

**Comment by thadius856** [comment]
I really don't think people are crazy about out logo. They intentionally remove it from their installs...

**Comment by mcangeli** [comment]
I know I'm not one of the "big three" but some insight...

Unless you're going to have a dedicated team or person thats creating the SD Cards/raspberry Pi's with it loaded and ready to go, its really not worth it to offer the pi's for sale or even the SD Cards with the images installed and ready for boot. 

There are issues with it that make it impractical (the big one being that a user can download and install raspbian in under an hour at home and in another 15 minutes have the site up and running. Its not worth it for some one (especially in the target market of the RP where everyone is about diy and doing it cheaper) to have to configure, and set up a pi for someone and then ship it to them.

The software is available for download from the site. The next step would be creating a debian package that could be installed via apt-get as part of the lamp install.

You really want to stay out of the hardware business.

The next item of custom boards or boards ready to go with the flowmeters...  again, I think that you're missing the target audience with this one. If someone wants a canned ready to go system, point them to kegbot. Custom boards are a pain to design, find a good manufacturer and then maintain an inventory. Its pointless to do orders of small amounts so unless you're moving large volumes of the boards (which, lets be honest is not too likely) its not worth it.

The area to focus on since the software is free and the hardware is cheap from so many sources, would be donations and a shop with things like stickers, shirts, cups, etc.

Cafepress is good for the things like shirts, cups, stickers, etc as you upload your image and put it on the items you want to sell and they do all the inventory and production. You make a cut (like $2 a shirt) and can set prices and offer specials, etc. I think zazzle is another type site. But again, like @thadius856 said, if people are removing the logo from their taplists, chances are outside of a small group of us, there isn't going to be much need for swag.

In the almost 10 years Linuxtracker.org has been online, I have brought in more money through google ads on the site than through selling LT branded swag. Most of the LT Swag I have sold is stuff I've bought to give away.

I think its absolutely ridiculous of HBT that they won't allow a link to a site thats taking donations or that has affiliate links but makes no money otherwise but its their site and their rules.

Something should be done to help cover basic costs like the site and domain.... but what that is and how to do it with in the HBT "code of ethics"

I would say dump the facebook ads. Focus on things like the r/homebrew, hbt, byo and the other homebrewing sites.

Nothing would be cooler than getting some press in an issue of zymurgy.

**Comment by thadius856** [comment]
I used to work for a company that contracted with Zazzle for product we couldn't produce.

Half of those orders came back as rejects and we had to re-do them. The customer didn't know we contracted out, so it made us look bad. Huge thumbs down on Zazzle.

**Comment by thadius856** [comment]
> The software is available for download from the site. The next step would be creating a debian package that could be installed via apt-get as part of the lamp install.

Yessss.

How do we make this happen? :D

**Comment by mcangeli** [comment]
The easy part would be creating the pkg file.

The hard part would be getting it added to the official raspbian repository… but let me do some research on this.

**Comment by mcangeli** [comment]
The other option would be to do something like they did with kegberry and make it an install.sh file that is run on the local machine that automatically downloads and installs everything.

**Comment by Skemp45** [comment]
ok, it looks like no one really wants to head this on or thinks its a good idea, cant blame me for testing the waters though ;) closing out issue

**Comment by thadius856** [comment]
Certainly do not blame you in the least.

If this was pitched when I as questioning staying on HBT, I'd have been all-in. Looking back, I'm pretty sure that would have been a mistake.

That said, our customers haven't been exactly as I'd hoped.

**Comment by Skemp45** [comment]
What do you mean by 

```
That said, our customers haven't been exactly as I'd hoped.
```

**Comment by thadius856** [comment]
Compared to our download numbers, we get little feedback. What we do get is usually asking for more features. Half of our support tickets have been people not reading the directions, when the very first sentence of the install instructions says to follow along carefully. A couple have even dug nails in deep and raked us across the coals when their desired feature/functionality didn't surface in v1.0.0.

**Comment by Skemp45** [comment]
Yeah, its super hard to please alot of people :/ as long as our true followers stay happy then we are good

**Comment by JayUnt** [comment]
Our true followers, yes.  But more importantly us.  If i wasn't interested in having this for myself, i doubt i would be as involved as i am, if at all.  But on the flip side, if no one besides us were interested, I would still do what I'm doing.  Though it does make it even sweater to see we have 190 likes on facebook (190?!? thats actually ridiculous)

**Comment by Skemp45** [comment]
RIGHT
