### ISSUE TITLE
Where to go next?

### ISSUE THREAD

**Issue by JayUnt** [RaspberryPints/RaspberryPints#251]
So it seems like we are at a standstill again.  The laravel conversion is complete, with the exception of the testing, but pretty much all of the code is there.  There is the performance issue which, I wasn't able to reproduce, but others said its too slow.

Was the move to laravel too much for this project?  Should we abort this and just go back with the original code, so we can get something out?  We moved to laravel to keep things clean and easy to update.  But if its too much of everyone and we aren't getting anywhere, where others can code, maybe we should consider going back.   It was very hacky but it moved as opposed to now.  

Thoughts?

**Comment by mcangeli** [comment]
I've been going through and reading the posts on HBT in the Rpints post,
and people have made a ton of changes (layout, additions, etc) that get
completely overwritten and harder to make with the move to laravel.

I haven't seen an issue with performance (once I got rid of the kegbot I
had installed on the rpi). My pi crashed for a bit and I just got it back
on line the other day, so I've been working on the install script for it.
My plan is to reinstall the pi and have the install.sh file do the complete
install of the lamp stack and the rpints code.

ideally, I think I can get it to where you download and run install.sh and
outside of a couple of prompts, it is setup and running with the test data.

**Comment by Boombrewer** [comment]
I'm also in the camp of questioning the laravel move. It seems to have stalled collaboration. And given most home brewers fall into the 'hacker' rather than 'coder' camp, it might be best leaving it to be hacked by others. Thad did start this as a project for others to toy with if I remember right.

**Comment by JayUnt** [comment]
our changes will probably totally break their code, which could cause backlash.  Its not a huge deal to me, but i dont want to screw people over and have them get mad at us.

And i was a big proponent of the move, but if im the only one who can work on it, and its causing a huge bottleneck and even making people not want to work on it, i think we should go back.  It wasnt a huge waste of time for me, because i got to learn laravel, so i wont be crying myself to sleep at night.

**Comment by Skemp45** [comment]
I agree, this project has taken a wrong turn and I know there are alot of people VERY interested in the next release and we kind of owe it to them to get it out there. Lets stick with the old code that everyone know and push forward with this thing

**Comment by Skemp45** [comment]
Let get a vote in here so we can get this back on track. I am for going back to old code

**Comment by Boombrewer** [comment]
Ok. So assuming no one has any major objections who feels comfortable going through the issues and purging the tasks that no longer apply?  I can do some but not all. 

I'm for old code also.

**Comment by Skemp45** [comment]
I can do a task cleanup when we have a final decision.

**Comment by Skemp45** [comment]
@mcangeli  and @JayUnt  and @thadius856  are you guys cool with sticking with old code?

**Comment by Skemp45** [comment]
OK, I took it appon myself to clear the issue board of clutterd issues that pose no value to moving us forward. You will see we went from 39 issues down to 8 issues  and we will add freshones as we see fit moving forward, but who is ready to crack down over the next month and whip this v2 out to the people!!!

**Comment by mcangeli** [comment]
I posted this in response to one of the other threads...

The move to a framework like laravel was debated for a while. We went back and forth on it. It had been decided to move to it to help development move along and make things easier for the devs.

And as far as maintaining the base code it's great.

The problem lies in two things... The first, there isn't a good way to handle themeing or customization. It takes too many steps with laravel to make it a unique install. Looking at the post on HBT,  people have changed the layouts beyond simply changing the background as they need to in order for it to fit their monitor or other setup. The laravel move could work if we developed a good, simple theme engine.

Second is the integration of other code or plugins. Having worked with @jayunt and @kerber on the laravel move and having developed the untappd integration I can say it's a pain in the ass at the moment. A simple plug in structure would need to be developed and in place as well as documented for people to use.

I don't think that the move to laravel should be totally dropped. I do think that for V2, we should evaluate things and perhaps roll out basic flow meters (the code works. I've been using it for a while now) and work on making the laravel branch more complete with the themeing and plugins.

We had said that v2 would be flow metering. The masses might rebel if it's not.

**Comment by JayUnt** [comment]
Yeah as much as it pains me to drop the laravel code (at least for now) i think its the best decision for this project for now.  The laravel change halted new development, so hopefully this will reinvigorate it.

**Comment by Boombrewer** [comment]
So basically you guys are saying we can have the best of both worlds.  We can develop the flow sensors with the old code now and release V2 in order to please the masses and continue to develop laravel to do everything the masses are hacking into the current code.  If that's the case, that has my vote (who doesn't like cake and eating it too).

I'll ask you smart guys this though.... if the move to laravel apparently stifled development the first time, what can we do to keep the same thing from happening later?  I read through the explanation of the MCV framework and it made sense to me.  But when I actually tried to get in there and do some coding, completely lost.  (and I have made progress in understanding code)  So is there a way to move to laravel and still enable development by everyone?

**Comment by paulcanning** [comment]
Ideally what you want is to move to an MCV framework and then get users to develop "plugins" for anything they have added themselves, rather then changing the core code (which they seem to be doing now, as there is only the core code to edit!)

**Comment by mcangeli** [comment]
Yes... But the problem with the current framework version is that there
isn't a plug in method developed. Nor is there a themeing method.

For version 2 people are expecting flow monitoring.

We should deliver that and continue to develop the framework version for
the next release.

**Comment by paulcanning** [comment]
I know.

My response was to Boombrewers question about how to make things easier in the future if you move to a MCV framework.

**Comment by Skemp45** [comment]
Alright @mcangeli you said you had this setup and running in your house. Can you take the time to write up a step by step on how you got this running, including steps for adding the board to the raspberry pi and adding the flow meter in? I will follow the steps and set mine up and take notes while doing it on what needs to be automated and I can get started on writing out the user interface for this so we can get this release out there.

**Comment by Boombrewer** [comment]
@Skemp45 I'm right there with you on testing that out.  I had part of it on mine for a bit but it lacked the front end.  I can help with the board and stuff if you want to get started.

**Comment by mcangeli** [comment]
The code I'm using is based off the database changes that Jayunt had made
for the framework version.

I'll have to see if I can update it to work with the older code again.

**Comment by mcangeli** [comment]
@Skemp45 can we close this issue?

**Comment by Skemp45** [comment]
Yup, good as closed
