### ISSUE TITLE
Setting up your flow meters 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#259]
This is the code I have for FlowMeter Keg Levels...

First things first:

Assemble the Alamode according to the user guide:
https://docs.google.com/document/d/1HBvd3KNmcs632ZgO6t_u37B-qwV6P9o9FQe62lGkumM/edit

The quick version is this:

on Page 7 follow the instructions to install the headers (requires solidering)

Open LXTerminal (or connect via ssh) and type following commands:

pi@raspberrypi ~ $ sudo apt-get update
pi@raspberrypi ~ $ sudo apt-get install arduino python-serial python-mysqldb php5-cli xdotool

To make the necessary changes for the Arduino IDE to recognize AlaMode, download AlaMode set up from the link given below.

https://github.com/wyolum/alamode/raw/master/bundles/alamode-setup.tar.gz

From the command line, unpack and install it:

pi@raspberrypi ~ $ tar -xvzf alamode-setup.tar.gz
pi@raspberrypi ~ $ cd alamode-setup
pi@raspberrypi ~ $ sudo ./setup

Then:
pi@raspberrypi ~ $ sudo shutdown -h now
(this halts the rPi so you can safely remove power)

To Power the Alamode and the rPi, set the 5V_link jumper to on (see page 11). This allows you to connect power to the alamode board 
to power both the alamode and the rPi. This is important as the flow meters will draw more power than the rPi can safely supply via GPIO

To connect the flow meter to the alamode:
Pin1(red) -> Ground
Pin2 (middle)-> Any digital pin 2-13. Be sure to set this at the top of the Arduino code
Pin3 -> VIN

Once the alamode has been seated on the rPi (on the gpio pins) and the flow meter has been attached you can power the 
rPi up. Plug the power in to the micro usb on the alamode and not the rPi.

Log in to the GUI on the rpi and go to the menu -> Programming -> arduino
This opens a program used to edit the ino file for arduino as well as compiler and uploader.
Click on file -> open
Browse to your raspberrypints directory, look for the arduino -> raspberrypints folder and select the raspberrypints.ino file
At the top of the file locate two lines:

//This line is the number of flow sensors connected.
const uint8_t numSensors = 4;
//This line initializes an array with the pins connected to the flow sensors
uint8_t pulsePin[] = {8,9,10,11};

Change the number of sensors to the total number of flow meters you have in line (in my case I have 4) and set the next one to the pin numbers that 
the meters are attached to (not the ground or vin). I started at 8 simply because it was easier to attach to these pins. MAKE A NOTE OF THE PINS AND TAPS
you will need this information later.

Save the file, do not close.
Go to Tools -> Board and select the Alamode
Go to Tools->Serial and click the box for the serial connection (there should only be one)
In the menu bar there is a button that is a circle with an arrow in it ->
Click that button to compile and upload the ino file to the Alamode board This is important, the alamode needs the code uploaded to it in order to 
read the flow meters. If you add meters you have to recompile and reupload

In phpmyadmin on your machine (if you haven't installed it yet, sudo apt-get install phpmyadmin then go to localhost/phpmyadmin)
You need to run:
ALTER TABLE pours ADD pinId INT( 11 ) NULL AFTER tapId;
ALTER TABLE taps ADD pinId INT( 11 ) NULL AFTER tapNumber;
INSERT INTO raspberrypints.config (id, configName, configValue, displayName, showOnPanel, createdDate, modifiedDate) VALUES (NULL, 'useFlowMeter', '0', 'Use Flow Monitoring', '1', NOW(), NOW());

Log in to the admin area of your raspberrypints install.
click on taps
edit the taps and add the pinId.

At this point you should be ready to run the python script.
In a terminal window,

pi@raspberrypi ~ $ cd /location/of/raspberrypints/python
pi@raspberrypi ~ $ python flow-meter.py

This will start the script. You will not see anything output until you actually pour a pint. When a pint is poured it passes the pin number and the pulse count
to a php script which then updates the pours table in the database and then refreshes the chromium browser on the localhost.
You should also see output on the terminal window where you started the python script.

**Comment by Skemp45** [comment]
Per @mcangeli

**Comment by Skemp45** [comment]
@mcangeli how did you hookup your flow meters in line? can you post a pic?

**Comment by mcangeli** [comment]
How do you mean? A photo of the flow meters on the hose?

**Comment by Skemp45** [comment]
YEah or just a description of how you set it up

**Comment by Boombrewer** [comment]
@Skemp45 
Here's a photo of mine.  I have connectors that I still need to add in close to each sensor so that I can just unplug it and pull it out for cleaning without pulling the whole run of wire out.  My Pi sits on top of my kegorator.
![image](https://cloud.githubusercontent.com/assets/6321429/3863656/50aae8e8-1f4c-11e4-9c22-c175c2efca2e.png)

**Comment by Boombrewer** [comment]
the feature-flow_monitor doesn't look like its been updated for a while (5 or 6 months).  So I'm not sure if that's the code we're supposed to be using or not.

When I go to my taps page, there is no pinId field to update.  Do I have the wrong code or am I missing something?

**Comment by mcangeli** [comment]
Yea I don't think that the git repo has been updated with my code.

Also you have to update your tables (that's in the instructions)

It's available in my repo

https://github.com/mcangeli/RaspberryPints/tree/feature-flowmeter

**Comment by Boombrewer** [comment]
Yeah, I updated my tables already.  I just need to update my code and I can start testing.  Thanks for the link.  I'll download and get started this week sometime.

**Comment by Skemp45** [comment]
Yeah I was having issues getting that merged in. Will take a look this week

**Comment by mcangeli** [comment]
Boombrewer, also run: ALTER TABLE
http://10.0.0.17/phpmyadmin/url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.5%2Fen%2Falter-table.html&token=5c0c3667b205c5af9fecee63b6ddbce7
 `pours` CHANGE `amountPoured` `amountPoured` FLOAT( 6, 3 ) NOT NULL

That way we can get a little more accurate with our pour counts.

**Comment by Skemp45** [comment]
@mcangeli  I merged in your pull request, can you please check to make sure everything is there and good to go. once that is done I will pull it down and run through an install following your instructions

**Comment by mcangeli** [comment]
Yea, it looks good.

**Comment by mcangeli** [comment]
@Skemp45 I tried this on a new pi today (I bought one of the new B+ models and it works well) and it worked good.

I'm still working on a better way to have the flow monitor.py script run at startup, but I would say we can post on the HBT post that v2 with the flow monitoring is available for testing as long as people understand there may be issues with it.

**Comment by Skemp45** [comment]
Let's just wait a make it solid and make it a release rather then some people getting got and some not. They will kill a good release!

**Comment by Boombrewer** [comment]
So I noticed that the initial volume is entered manually. We discussed basing this off of weight (and other data points). Do we still want to do this? And if so, version 2?  If not we may want to add a "How to" on calculating volume from weight. Just some thoughts.

**Comment by mcangeli** [comment]
I went with the code already in place. (I grabbed a fresh copy of the master repo and added the flow meter code)

So that's how it's currently being done I believe. I'd leave it as it is. People know that they either have 5 or 3 gallons.

I do plan on working on the code to update the database and the code to more in line with what was done with the framework version (using liter instead of gallons and having the code handle the conversion).

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:08/12/2014  12:23 AM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Setting up your flow meters  (#259) </div><div>
</div>So I noticed that the initial volume is entered manually. We discussed basing this off of weight (and other data points). Do we still want to do this? And if so, version 2? If not we may want to add a "How to" on calculating volume from weight. Just some thoughts.

**Comment by mcangeli** [comment]
@Skemp45 you ok with me posting an update to the HBT thread letting people know where the flow meters stand and the equipment/setup of it?

**Comment by Skemp45** [comment]
Yeah for sure just don't say to go download it just yet. Let them know the equipment needed and how close we are!!

**Comment by day-trippr** [comment]
LOL! Part numbers and perhaps a source that doesn't want actual body parts in exchange would be nice ;)

Cheers!

**Comment by Boombrewer** [comment]
@mcangeli I am with you.  I think its good the way you have it especially for V2.  I'm not even sure we should change it later or just give the option.  Maybe have two blocks (volume and keg weight) that an entry in either will satisfy the field requirement.   Anyways.... I think we'll all agree that's a conversation for V3.

**Comment by mcangeli** [comment]
@day-tripper I'll be working on a cleaner and more precise install document (screen shots and all) closer to release. The board however is http://wyolum.com/projects/alamode/ and plugs right on the pi's gpio pins.

@boombrewer there is a spot in the keg table for weight of empty keg. Plus the start volume in the taps field when you tap a keg.

There were some changes in the framework version that made this easier.

**Comment by day-trippr** [comment]
I've actually had R'Pints running since April with a system on my keezer and another in my office, with an AlaMode on each waiting patiently for V2 :) There's a lot of us over at HBT with similar setups, so from here it's pretty much going to come down to how to plumb the flowmeters.

Cheers!

[edit] With HBT's help I found the Guest 3/8" female BSP to 3/8" OD tubing coupler part number PI451213S, as well as the Guest 3/8" OD tube to 1/4" barb fitting part number PI251208S. Then the ebay seller responded that a pair of the couplers are included with his SF800 LP meters (likely the ones Swissflow shipped 'em with) so I only had to order up the barbed fitting (sweet! $50 saved!)

Thinking about making a patch panel to convert the six three-conductor flat cables to some kind 8 pin DIN bulkhead connector I can put through the back of my keezer lid to get to the AlaMode...

**Comment by Boombrewer** [comment]
Any else see sporadic behavior?  I wasn't having much luck and my wife walks out to pour me a pint and suddenly it registers and updates.  WTH?!  And now I can't get it to do anything.

Should the python script be running in the background?  When I open the terminal window to start the python file, it just goes to the next line but not to another command line.  Normal?  And does the process stop (potentially) when you close the window?
^^^^^^^ answered my own question.  Closing the terminal window terminates the process.  The python script needs to be running via an init.d file on startup.

**Comment by Boombrewer** [comment]
So the init.d file from issue #194 still work?  That would be a way to eliminate some of the potential issues of starting the python script.  (am I way behind the power curve on this?)

**Comment by mcangeli** [comment]
I wasn't having any luck with the init.d script yet and yes.

When you run python flow.py it will sit there until a pour is registered.

**Comment by Boombrewer** [comment]
Ok.  So I have all 4 sensors working but one of the four is reading really high.  Like an 8oz mug registers as 178oz pour.  Any ideas why only one sensor would be doing this?  I haven't started into verifying the calibration (precision of pours) yet since I'm trying to kick two kegs.  But this is obviously way off.

And yes, the sensors are all the same.

**Comment by Skemp45** [comment]
Double check your wires on the one that is reading high, I run temp probes on one of my pis and one will read high if the wires are loose

**Comment by mcangeli** [comment]
I have one that does that too and I'm seeing phantom pulls and kicks as well. 

When I clean my lines next I'm checking all the connections for air.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:08/15/2014  9:15 PM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Setting up your flow meters (#259) </div><div>
</div>Ok. So I have all 4 sensors working but one of the four is reading really high. Like an 8oz mug registers as 178oz pour. Any ideas why only one sensor would be doing this? I haven't started into verifying the calibration (precision of pours) yet since I'm trying to kick two kegs. But this is obviously way off.

**Comment by Boombrewer** [comment]
Hmmm.... I'm about to have 3 of my four kegs kicked at the same time and I'll check for that.  But I don't think its an air issue.  The air seems to clear out of the lines pretty quickly after initial hookup.

What creates the 'kick' signal and what does that signal create on the taplist?  I was just assuming when the amount poured exceeds the starting amount the icon goes to "MT".  Maybe I need to look at the code again a little closer.

**Comment by mcangeli** [comment]
It doesn't do anything presently on the site.

A kick is signaled when the pulse count goes over a certain amount.

I'd have to look at the arduino code.

**Comment by Skemp45** [comment]
Alright, so I set it up tonight start to finish:

It works great!! 

Issues I ran into

1.) I dropped my soldering iron and caught it by the neck _OUCH_ this set me back 10 minutes.
2.) Page was not refreshing, had to adjust perms on the refresh.sh script. 
3.) I did not have the proper fittings or hose for my keg to put it inline so I did a makeshift job and had the co2 high. This gave me semi inaccurate reads <--- I like this because it will help people makesure their beer is coming out at the right psi, We solved 2 problems with 1 tool ;) 

Great work fellas. I want to go through and do some cleanup but I think we are close to launch date. Lets say mid week next week we sit down and choose a launch date. I say before the end of aug!

**Comment by mcangeli** [comment]
Were the instructions clear?

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Skemp45 notifications@github.com </div><div>Date:08/16/2014  2:46 AM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Setting up your flow meters (#259) </div><div>
</div>Alright, so I set it up tonight start to finish:

It works great!!

Issues I ran into

1.) I dropped my soldering iron and caught it by the neck OUCH this set me back 10 minutes.
2.) Page was not refreshing, had to adjust perms on the refresh.sh script. 
3.) I did not have the proper fittings or hose for my keg to put it inline so I did a makeshift job and had the co2 high. This gave me semi inaccurate reads <--- I like this because it will help people makesure their beer is coming out at the right psi, We solved 2 problems with 1 tool ;)

Great work fellas. I want to go through and do some cleanup but I think we are close to launch date. Lets say mid week next week we sit down and choose a launch date. I say before the end of aug!

**Comment by Skemp45** [comment]
Yeah, I will add pictures to it and I think that will make it even easier nice work man

**Comment by Boombrewer** [comment]
So I figured out pin 11 on my alamode has some issues.  Got it all sorted out (using 4-7).  Everything seems to work fine except I'm noticing the quantity is doubled.  I'm pouring 8oz (by measurement) and its registering 16oz utilizing cleaning solution (low concentration PBW and water).  I'll keg a hefe and pale ale tonight and see if that's better.  And measure my cream ale on nitrogen.

**Comment by mcangeli** [comment]
Let me double check my math.... (it was easy in the laravel version, not so much in this one because it uses gallons instead of ounces or something... ;) )

**Comment by mcangeli** [comment]
Boombrewer, run:
ALTER TABLE  `pours` ADD  `pulses` INT( 6 ) NOT NULL AFTER  `amountPoured`;

in phpmyadmin.
Download the new pours.php file and try that. Let me know if that works. I think I had the math wrong. ;)

**Comment by Boombrewer** [comment]
update the pours.php in the includes folder?  I did that and got a PHP parse error for line 55.

**Comment by mcangeli** [comment]
Fixed. You can either download the updated pours.php file or edit it in nano and remove the */ a few lines above the refresh call.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:08/17/2014  1:02 AM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Setting up your flow meters  (#259) </div><div>
</div>update the pours.php in the includes folder? I did that and got a PHP parse error for line 55.

**Comment by Boombrewer** [comment]
PHP parse error line 61.  unexpected }

looks like its really a { on 56 instead....

**Comment by Boombrewer** [comment]
Nope.  Fixed it.  Add a { to line 57.  You just missed the open bracket.

By the way, it works and the math is now correct.  Nicely done my good man.  Thank you.  I'll continue testing.

**Comment by mcangeli** [comment]
Nah, it was at 61. Totally unneeded.

**Comment by mcangeli** [comment]
Well, adding the one at 57 does "fix" the issue, but removing the one on line 61 is cleaner. The brackets aren't needed in that section (and may(?) affect the way the refresh script is called.

**Comment by Boombrewer** [comment]
And that's why I leave the code troubleshooting to the experts.

Does anyone have a working init.d that I can run to finish testing?

**Comment by mcangeli** [comment]
@boombrewer let me know if you notice any other issues.

**Comment by Boombrewer** [comment]
@mcangeli No issues so far.  I really need a way to run the python script in the background.  Then I'm going to check the accuracy across a few types of beer.  Maybe I'll toy around with hacking an init.d file.

I've found on mine that pins 5-10 work the best.  Not sure why 4 doesn't work and I see that 13 is used in the arduino script.  My pin 11 is messed up and I haven't checked 12 yet.  I think passing some suggestions to the users might be a good idea.

**Comment by mcangeli** [comment]
@Boombrewer try adding:

@/usr/bin/python /var/www/python/flow_monitor.py 

to the /etc/xdg/lxsession/LXDG/autostart file _AFTER_ the line for the browser

That _should_ get rid of the need for the init.d script and it appears to be updating the database correctly.

**Comment by day-trippr** [comment]
Quickie question to whomever owns the AVR code: are all of the pins set aside for flow meter data inputs configured with pull-ups? 

I ask because I whipped up a little patch adapter using an IDE cable as a temporary means of connecting flow meters to AlaMode (the flat cable shouldn't cause too much havoc with the keezer lid seal), and I included pull-ups on the data lines. Those might be redundant if the AVR inputs are configured with pull-ups. 

On that point, the ATmega328p Rpu spec ranges from 20K to 50K, an order of magnitude plus higher than what Swissflow recommends at 2.2K. Anyone scoped an operating meter signal to see what it looks like? Or will I be the first :)

![image](https://cloud.githubusercontent.com/assets/6963379/3960597/943b031e-2743-11e4-96b9-7857c1aa1e1d.png)

![image](https://cloud.githubusercontent.com/assets/6963379/3960749/15000592-2746-11e4-988a-25dcd3724a90.png)

Cheers!

**Comment by Boombrewer** [comment]
@mcangeli Nope.  Didn't work for whatever reason.  Here's a copy of my autostart file - did I miss something?

---

@lxpanel --profile LXDE
@pcmanfm --desktop --profile LXDE
@xscreensaver -no-splash

@xset s off

@xset -dpms

#@xset s noblank

@chromium --kiosk localhost
@/usr/bin/python /var/www/python/flow_monitor.py

sudo python pir_run.py

---

Shouldn't I just be able to run flow_monitor.py like I run pir_run.py?  Or do I need an "&" at the end to tell it to run in the background?

**Comment by mcangeli** [comment]
You might want an & to tell it to run in the background.

In the flow_monitor.py file around line 45 drop the .. and put in the full location of your raspberry pints install (/var/www)

The reboot and see if that does it.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:08/19/2014  1:02 AM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Setting up your flow meters  (#259) </div><div>
</div>@mcangeli Nope. Didn't work for whatever reason. Here's a copy of my autostart file - did I miss something?

@lxpanel --profile LXDE
@pcmanfm --desktop --profile LXDE
@xscreensaver -no-splash

@xset s off

@xset -dpms

#@xset s noblank

@chromium --kiosk localhost
@/usr/bin/python /var/www/python/flow_monitor.py

sudo python pir_run.py

Shouldn't I just be able to run flow_monitor.py like I run pir_run.py? Or do I need an "&" at the end to tell it to run in the background?

**Comment by Boombrewer** [comment]
@mcangeli Yep - that fixed it.  Thanks.  Should that be modified in the code being released?

**Comment by mcangeli** [comment]
Already did it in flow meter branch

**Comment by Skemp45** [comment]
Closing as this is now a how to guide
