### ISSUE TITLE
Keep an eye on this one...

### ISSUE THREAD

**Issue by mcangeli** [RaspberryPints/RaspberryPints#264]
Just wanted to post this here to keep an eye on it....

http://www.homebrewtalk.com/f51/linux-coldfusion-diy-tap-display-project-485122/

He's working on a taplist to display on a webserver in coldfusion (why coldfusion I do not know).

Some different ideas about the layout in there, may want to come back to that when working on the themeing for the next version.

**Comment by Skemp45** [comment]
Took everything I had not to comment on that thread lol........ Nothing to worry about we will still control the #1 spot for open source digital taplists. Wait till we release these flow meters!!!!!!

**Comment by Skemp45** [comment]
Also google Digital Tap List ;)

**Comment by Boombrewer** [comment]
That looks very similar to Yardhouse's displays.  Good for him but he obviously didn't use google first (or forum search).  And I'm shocked a 'web-designer' thought the RPi was a PITA.

**Comment by Skemp45** [comment]
HAHAHAHHAHA Competition is no longer
Straight from his thread.

Ok - so here's what I've decided to do:

Eliminate ALL the confusion of setting up a server, Linux, Coldfusion, SQL, licensing issues, programming, command lines, etc...

The service is going to be web-based, for a small annual subscription fee. I'm thinking of also offering a free service with ads everywhere. I hate ads as much as I hate freeloaders lol.

So here it is:
http://www.mytapdisplay.com

Just bring your own TV and a source (old laptop/desktop, old game system with a browser, a Raspberry Pi, Google Chromecast, etc...), and leave the rest to the service.

Log on from anywhere to configure your settings, change beers, and voila! The page source is set to refresh itself every 5 minutes to not only update, but also so that Flash doesn't freak out if it's open for days.

I'm looking into selling preconfigured RaspberryPi units that fire up like an appliance - you turn your TV on, it turns on the Pi, which goes straight to your tap display page automatically.

Also need to do some further R&D with Chromecast. I'm looking for a solid standalone device that can just sit there and display a browser. Bonus points for a preconfigureable home page.
n

**Comment by day-trippr** [comment]
Beat me to this. The Disinterest Level will now be stratospheric...

Cheers!

**Comment by mcangeli** [comment]
Well, thats gonna rain on a lot of people's parades. Rpints is still
cheaper then, and better in that regard.

**Comment by Skemp45** [comment]
comment was removed ...... :+1:

**Comment by thadius856** [comment]
Can't seem to access the link. Was it taken down?

**Comment by thadius856** [comment]
Nevermind. My phone must have hiccuped.

**Comment by Skemp45** [comment]
lol

**Comment by mcangeli** [comment]
He removed the post where he talks about charging and the link, but then posted about free trials.

Maybe I'll do up a layout the way he wanted it just to show the flexibility. 

We should look at creating a gallery for sharing rpints customization.

**Comment by Skemp45** [comment]
We can totally make a gallery on the official page

**Comment by Boombrewer** [comment]
How hard would it be to flip the orientation to vertical columns like he's talking about?  I personally wouldn't use it but it might be worth polling the users to gauge the interest.  I think in a place like Yardhouse, its a good idea but its limited in use to the homebrewer.

**Comment by thadius856** [comment]
I think first step towards a vertical layout would be to make all columns
toggle in the admin panel. That would allow users that want a horizontal
layout to fill the width of a horizontal screen. Next logical step would be
to make the front end skinnable, maybe provide a sample vertical layout.
Point being, if the front end layout is made skinnable, and the
extensibility stable between versions, advanced users could produce their
own skins and share them... potentially through our site?

**Comment by Boombrewer** [comment]
Yeah, but first question to answer is whether or not people want it.

**Comment by Skemp45** [comment]
You are both right, if people want it let's make it and 2.) we need to have a option in the personalize section to choose vertical rather than horizontal. We already have a function for this, switching style.css if you have a 4k monitor. So we can just supply a new style.css if you want a vertical taplist.

**Comment by thadius856** [comment]
There ya go.

Perhaps we just need to have the back end scan a subfolder for CSS files,
then list all found files. That way, all a user would have to do is
download the "skin" to the CSS folder and away they go.

How to do this? Not a clue.

**Comment by mcangeli** [comment]
That's the easy part Thad.

I plan on working on themeing as part of the next version.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: thadius856 notifications@github.com </div><div>Date:08/21/2014  2:02 AM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Keep an eye on this one... (#264) </div><div>
</div>There ya go.

Perhaps we just need to have the back end scan a subfolder for CSS files,
then list all found files. That way, all a user would have to do is
download the "skin" to the CSS folder and away they go.

How to do this? Not a clue.

**Comment by Skemp45** [comment]
if you look in the feature-admin_theme_color branch I already do this.

**Comment by Skemp45** [comment]
header.php
`$sql="SELECT configValue FROM config WHERE configName ='".ConfigNames::AdminThemeColor."'";
$result=mysql_query($sql);
$stylesheet=mysql_fetch_array($result);`

`<link href="<?php echo $stylesheet['configValue']?>" rel="stylesheet" type="text/css" />`

config_names.php
`const AdminThemeColor = 'adminThemeColor';`

**Comment by mcangeli** [comment]
I'm going to close this as its totally off track at this point. :8ball:
