### ISSUE TITLE
ALERT!!!! ISSUE 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#283]
FROM: DrunkleJon

Not a complaint, just an observation, but
It looks like I have to manually run
Quote:
cd /var/www/python
python flow_monitor.py &
every time I boot if I want pours to register. I checked twice in the ...LXDE/autostart and everything is as described.

Quote:
...
@chromium --kiosk localhost
@/usr/bin/python /var/www/python/flow_monitor.py &
I just navigate to '/var/www/python/' and run 'python flow_monitor.py &' and everything registers correctly when I pour.

Thanks again for all your help. Now to drink all this beer I poured. Oh what a difficult life I live.

**Comment by Skemp45** [comment]
Can anyone duplicate this

**Comment by mcangeli** [comment]
Yea, I was having issues as well.

If it's the last line in autostart autostart and there is no & it works ok.

**Comment by raysmithtx** [comment]
Not directly to the new release but there have been a few changes since the original write up for Version 1.
Raspi config now has an option that you have to select to boot to the gui. The options are boot to scratch, boot to the terminal and boot to the gui. Apparently the default is boot to the terminal. If you do that then you will have to log in and then select Startx to get to the gui.

Second, when installing the databases and you have to select Apache. The Apache is highlighted with a red box but it is NOT selected. You have to hit the spacebar to select install Apache before continuing. If you don't do that then you will not be able to get to localhost/phpmyadmin.

**Comment by mcangeli** [comment]
Instead of adding the line to autostart to run the python, another option is to add to the crontab:

@reboot python /home/pi/MyScript.py &

Where the /home/pi/myscript.py points to the flow_monitor.py script.

I haven't tested this yet.

**Comment by Skemp45** [comment]
Removing the & worked for him

**Comment by Boombrewer** [comment]
I had to remove mine as well (thought we discussed this already - my apologies).  My runs fine from boot and for reference / comparison:

This is my whole file from /etc/xdg/lxsession/LXDE/autostart

---

@lxpanel --profile LXDE
@pcmanfm --desktop --profile LXDE
@xscreensaver -no-splash

@xset s off

@xset -dpms

#@xset s noblank

@chromium --kiosk localhost
@/usr/bin/python /var/www/python/flow_monitor.py

sudo python pir_run.py

---

**Comment by Skemp45** [comment]
removing & resolved. closing
