### ISSUE TITLE
Tap List does not update in V2.0

### ISSUE THREAD

**Issue by funkt4life** [RaspberryPints/RaspberryPints#291]
Hello.

I cannot get my taplist to update when I tap a keg.  It says the keg is serving but my taps remain empty.  Ideas?

**Comment by day-trippr** [comment]
Whoof. I misread that to mean they weren't updating on pours.
Haven't had the empty tap list bug, but before HBT crashed tonight I think I saw someone else with the same problem.

Are you running flow meters?  I just noticed that mcangeli has an update for tap.php that addresses that problem for non-flow-meter configurations.

Cheers

**Comment by mcangeli** [comment]
Yea, there is a fix for the issue with the tap list not allowing a new keg to be tapped if the flow meters are not being used.

**Comment by funkt4life** [comment]
Hi.

Thanks for your reply. As I wait for the flow meters I would like to use
the raspints without meterage.

Can you please point me in the direction of this fix?

On Wednesday, September 3, 2014, mcangeli notifications@github.com wrote:

> Yea, there is a fix for the issue with the tap list not allowing a new keg
> to be tapped if the flow meters are not being used.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RaspberryPints/RaspberryPints/issues/291#issuecomment-54235159
> .

## 

Sincerely,
- Levi Fried

**Comment by Boombrewer** [comment]
I think the new index.php file has the fix but I'm not positive.  If you want to try downloading that one from the V2 branch, it might help.  But make sure you save the old file since I'm not sure if the most recent changes rely on other file changes as well.  Just something to try until real experts weigh-in.

**Comment by mcangeli** [comment]
No. It isnt the index.php. That has the fix for starting a keg with less than the keg volume (2.5 gal in a 5 gal keg)

The file with the fix is the /admin/includes/models/tap.php file.

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Boombrewer notifications@github.com </div><div>Date:09/03/2014  1:36 AM  (GMT-05:00) </div><div>To: RaspberryPints/RaspberryPints RaspberryPints@noreply.github.com </div><div>Cc: mcangeli mcangeli@gmail.com </div><div>Subject: Re: [RaspberryPints] Tap List does not update in V2.0 (#291) </div><div>
</div>I think the new index.php file has the fix but I'm not positive. If you want to try downloading that one from the V2 branch, it might help. But make sure you save the old file since I'm not sure if the most recent changes rely on other file changes as well. Just something to try until real experts weigh-in.

**Comment by mcangeli** [comment]
Replace your admin/includes/models/tap.php file with this one:
https://github.com/RaspberryPints/RaspberryPints/blob/Version2/admin/includes/models/tap.php
