### ISSUE TITLE
Replace Static Infographics with CSS-fill Versions

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#3]
Static, manually generated infographics are unsustainable.

Replace all static infographics with CSS-filled versions to save space and time.

**Comment by JayUnt** [comment]
Hey Thadius, I need to get the image of the glass that is laying on its side from the abv/offthechart.png image.  You can either commit that by itself or send me the layered file and i can pull it out.

Thanks,

**Comment by thadius856** [comment]
Hrm. I think I'll have to re-create it. I had a few when making that image,
and had to butcher the alpha on teh white fill to make it look decent. :S

**Comment by thadius856** [comment]
Yeah man, I'll have to hack at it again tomorrow. I owe the wife a date and movie tonight. Sry.

**Comment by JayUnt** [comment]
No sweat. I got the rest of the abv images setup and that will be an easy
update once I get that image. I also did the keg amount and am working in
the ibu now. I'll probably stop after that fit the night to pay attention
to my wifey too.

**Comment by JayUnt** [comment]
I'm pretty much done with these, I just need to create a large hops icon for the off the charts ibu and the spilled beer for the abv (or if you can get it for me easily that will be awesome).   When i was working on this, i did it directly on the master.  Would you prefer me to take a fork and copy it all over there, instead of committing to the master? Then it will be more like the other developers.

**Comment by thadius856** [comment]
Jay, the large hops icon was just the small hops icon at 300% or 400% or somesuch. Since the source was 1500px tall, it didn't cause any noticeable loss to blow it up 300%+, then shrink it back to 100px tall.

**Comment by thadius856** [comment]
Merged your fork back into the master. Keep up the great work!

**Comment by JayUnt** [comment]
Thanks.  This is an awesome project.  I cant wait to see how the flow sensors work and then ill get myself a raspberry pi to actually build my own.

**Comment by thadius856** [comment]
This code went _poof_ and is nowhere to be found as of Commit 38. Will have to dig back in the revisions and re-implement.

I'll start on this first thing Saturday morning if nobody else does first.

**Comment by JayUnt** [comment]
I wonder if it would be easier if we all worked on the master instead of making forks.  It doesn't look like GitHub is doing as good as a job at merging as we thought it would.  If we all worked on the master, it would be on the person committing their code to make sure it worked.  They would do an update to the most recent code in master before they commit their code and fix anything that needs to be fixed before committing.  

Thats how i usually use repositories.  Forks/Branches are more for big development changes where you don't want to break other people's code for a long time if it takes a long time to develop.  All of these tasks are going really fast, so it shouldn't be an issue.

**Comment by thadius856** [comment]
Agreed. We went to forks because of warnings that'd fuck each other up and lose code if we didn't.

Guest what. We're fucking each other up and losing code with forks.

Back to plain 'n' simple. Edit the master at *will. Just please check your changes in browser before you commit.

**Comment by thadius856** [comment]
Fixed in last commit.

**Comment by JayUnt** [comment]
yeah, you live and you learn.  after the last one gets pull (it should work automagically) im going to delete my fork and just work off of the master.
