### ISSUE TITLE
Phone Application 

### ISSUE THREAD

**Issue by Skemp45** [RaspberryPints/RaspberryPints#70]
This may be down the road a few versions but I feel we could easily make a app for the brewery owners or homebrewers to manage their taplist from their phone. 

We would really just duplicate the admin panel but put it into an app!

**Comment by thadius856** [comment]
Maybe a mobile version would suffice?

Not super keen on the idea of this (RPints) being used in a professional brewery. I don't feel like we should be competing with the commercially available versions.

**Comment by Skemp45** [comment]
Do we want to limit it though? as far as letting brewery's use it if they want?

**Comment by Skemp45** [comment]
What loss do we have if they do use it? What gain do we have if they dont?

**Comment by thadius856** [comment]
> What loss do we have if they do use it?

Well, there's for-profit companies trying to make a buck on their products already. I don't wanna take food out of their mouths.

> What gain do we have if they dont?

I just don't want forum post spam like "ZOMG I LOADED THIS AT MY BRWEERYERYERY AND IT BROKE AND THE DOORS OPEN IN 3 MINUTES AND I NEED. HELP.. NOW... THIS PRODUCT SUCKS>>> NOT SUPPORT ZOMGWTFBBQ"

**Comment by Skemp45** [comment]
BBQ AHHHHHHHHHHH

**Comment by Boombrewer** [comment]
Well, I think you're not going to stop it from going into any tap room (private or otherwise).  So to me, you limit your liability by stating its not intended for commercial use and no support for that will be provided.  I'm clearly not a lawyer but something along those lines should cover you if other commercial product companies get up in arms and also make you feel better about deleting all those BBQ complaints.

But we all know word of this is going to spread like wildfire and eventually some small tap room owner is going to be like, "Damn!  that's nice!" and you guys will walk in one day and say, "Yeah, we did a damn fine job with that"

**Comment by Skemp45** [comment]
Yeah, I just feel it would be awesome to see this product in tap rooms and brewery's

**Comment by Boombrewer** [comment]
I think you're going to see it there whether you want it there or not.  People are going to do with it whatever they please.  Just because you say no or its not meant for that, doesn't mean they won't do it.  There's nothing to stop them from following the directions and hooking up a 55" LED above the bar just like I'm hooking up a 19" above my kegorator.  Where there's a will, there's a way.

**Comment by JayUnt** [comment]
I agree with just a mobile site, no need to make a whole app.  We can just make the admin responsive to different window sizes and be done with it.

**Comment by jkurl** [comment]
IOS has the ability to save the webpage as a app so you can quickly access it. I am not sure if android, windows or blackberry has the same ability.  I had a android phone for a while but never played around to see if that setting was available.

**Comment by Skemp45** [comment]
Calling this closed

**Comment by thadius856** [comment]
So, did we decide we needed a mobile website layout, an app, or both?

**Comment by JayUnt** [comment]
I don't know app development, so I wouldn't be of help if we went that
route.  But that's fine if that went to someone else.  If we did a
responsive admin section, I could work on it.

**Comment by Skemp45** [comment]
For now let's just kept it responsive mobile version
