### ISSUE TITLE
SRM Tops out at 40 SRM

### ISSUE THREAD

**Issue by thadius856** [RaspberryPints/RaspberryPints#83]
SRM tops out at 40. Anything 40.1 and higher is transparent.

**Comment by JayUnt** [comment]
The srm to rgb conversion place that i got the list from only went up to 40.  We can either add more rows, or just but a check that if its over 40, we make it black.

**Comment by Skemp45** [comment]
^ make it black over 40

**Comment by thadius856** [comment]
Vote for check, use SRM 40 if over 40. The color at 40 SRM is so close to black it's not even visually differentiated (around rgb 5-5-5 IIRC) from pure black.

Tried to code the check myself, but I got frustrated when I couldn't figure out how to code "use 40 SRM" in PHP.

**Comment by JayUnt** [comment]
Im going to just make it black. To do the 40 srm value we would have to either return that value with the along with the right rgb value for all, or do an extra call to get the max one.  But to the the black, i can just hard code 0,0,0 as the color.

**Comment by thadius856** [comment]
Cheater! I could have hacked that :P

**Comment by JayUnt** [comment]
Work smarter not harder :)

But i actually didn't even commit it yet because i never ran through the
install.  Im getting a little slackish even though we are getting to the
end.  You can do it if you want, or i will finish it up tonight.

The other thing i thought of, which maybe isnt for this release. Is the
juice and seltzer colors.  Do we want to allow them to choose a color if
its not a beer?  Or should we just limit them to making it a beer with 0
SRM and we make it white, or something like that?

On Mon, Feb 3, 2014 at 8:25 PM, thadius856 notifications@github.com wrote:

> Cheater! I could have hacked that :P
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/RaspberryPints/RaspberryPints/issues/83#issuecomment-34021708
> .

## 

Jason Unterman

**Comment by thadius856** [comment]
I had additional colors planned for v2, along with...

A bevTypes table. Beer, wine, kombucha, soda, milkshakes, canine diarrhea,
whatever.

**Comment by Skemp45** [comment]
https://www.youtube.com/watch?v=pGL2rytTraA

**Comment by thadius856** [comment]
Tested. Closing as completed.
